import React, { createContext, useContext, useState } from "react";

const LanguageContext = createContext();

export const translations = {
  fr: {
    nav: {
      home: "Accueil",
      services: "Services",
      luxopuncture: "Luxopuncture",
      about: "À Propos",
      contact: "Contact",
      rdv: "Prendre RDV",
      pricing: "Tarifs",
    },
    hero: {
      badge: "Docteur en Pharmacie",
      title1: "Retrouvez Équilibre",
      title2: "& Bien-être au Naturel",
      subtitle: "Nutrition clinique, suivi diététique personnalisé et luxopuncture. Une approche unique fondée sur l'expertise pharmaceutique, au cœur de Tel Aviv.",
      cta: "Prendre Rendez-vous",
      services: "Découvrir les Services",
      certified: "Docteur en pharmacie",
      centre: "DIPLÔME UNIVERSITAIRE INTERNATIONAL HÔPITAL BICHAT PARIS",
      stat1: "Ans d'expérience",
      stat2: "Clinique privée",
      stat3: "En France",
      stat3label: "Formée",
      luxoCardDesc: "Technique de rayonnement infrarouge non invasive pour le bien-être global",
    },
    services: {
    badge: "Écosystème de soins",
    title: "Vos Objectifs, Notre Expertise",
    subtitle: "Chaque traitement est conçu avec la rigueur d'un docteur en pharmacie et la douceur d'une approche holistique.",
    more: "Voir tous les services",
    pageTitle: "L'Excellence au Service de Votre Santé",
    pageSubtitle: "Une expertise clinique complète, de la nutrition de précision à la luxopuncture, conçue avec la rigueur d'un Docteur en Pharmacie.",
      pageLabel: "Nos Services",
      cta: "Prêt(e) à Commencer ?",
      ctaDesc: "Chaque parcours commence par une première consultation. Prenez rendez-vous pour découvrir le programme adapté à vos besoins.",
      ctaBtn: "Réserver Ma Consultation",
      rdvBtn: "Prendre Rendez-vous",
    },
    process: {
    badge: "Protocole de soin",
    title: "Votre Parcours de Soins : La Méthode Ronit Kalfon",
    subtitle: "Un accompagnement de précision, étape par étape, pour une transformation durable.",
    step: "Étape",
    s1title: "Analyse Approfondie",
    s1desc: "Bilan complet intégrant votre historique médical, vos habitudes alimentaires et vos objectifs personnels.",
    s1detail: "Explorations biologiques et anamnèse pharmaceutique",
    s2title: "Optimisation de l'Équilibre Biologique",
    s2desc: "Élaboration de votre protocole nutritionnel de précision. Ici, nous ne parlons pas de régime, mais de rééquilibrage alimentaire : chaque recommandation est ajustée pour stabiliser votre glycémie et optimiser vos fonctions vitales sans carence.",
    s2detail: "Micro et macronutriments dosés au plus juste",
    s3title: "Rééquilibrage Endocrinien (Luxopuncture)",
    s3desc: "Stimuler des points réflexes par rayonnement infrarouge non invasif. Réguler naturellement la satiété, le sommeil et le stress, créant un terrain favorable à la réussite de votre protocole.",
    s3detail: "Infrarouge non invasif sur les méridiens",
    s4title: "Vitalité Durable",
    s4desc: "Suivi continu et ajustements pour garantir des résultats pérennes et un bien-être au quotidien.",
    s4detail: "Consultations de suivi et réévaluation",
    },
    clinic: {
    badge: "Notre Espace",
    title: "Une Expertise Clinique au Cœur de Tel Aviv",
    desc: "Dans un cadre calme et confidentiel, le Dr Kalfon reçoit ses patients sur rendez-vous pour des analyses approfondies. Chaque prise en charge est strictement individuelle, garantissant le respect du secret médical et le confort absolu du patient.",
    f1title: "Suivi Thérapeutique Individualisé",
    f1desc: "Chaque séance est ajustée à votre métabolisme, vos antécédents et vos objectifs.",
    f2title: "Cabinet sur Rendez-vous",
    f2desc: "Situé au cœur de Tel Aviv, un espace alliant haute accessibilité et discrétion.",
    f3title: "Environnement de Soin Apaisant",
    f3desc: "Un cadre serein, conçu pour la tranquillité et la qualité de l'accompagnement.",
    },
    cta: {
      title1: "Commencez Votre Transformation",
      title2: "Dès Aujourd'hui",
      subtitle: "Prenez rendez-vous pour une première consultation et découvrez comment l'alliance de la science et de l'innovation peut transformer votre bien-être.",
      btn: "Prendre Rendez-vous",
    },
    contact: {
      serviceOptions: [
        { value: "nutrition", label: "Nutrition & Suivi Diététique" },
        { value: "luxopuncture_weight", label: "Luxopuncture — Perte de Poids" },
        { value: "luxopuncture_smoking", label: "Luxopuncture — Arrêt du Tabac" },
        { value: "luxopuncture_addiction", label: "Luxopuncture — Addictions" },
        { value: "luxopuncture_sleep", label: "Luxopuncture — Sommeil" },
        { value: "luxopuncture_relaxation", label: "Luxopuncture — Relaxation" },
        { value: "luxopuncture_rejuvenation", label: "Luxopuncture — Rajeunissement Facial" },
      ],
      label: "Contact",
      title: "Prenez Rendez-vous",
      pageSubtitle: "Contactez-nous pour planifier votre première consultation ou pour toute question sur nos services.",
      subtitle: "Remplissez le formulaire ci-dessous et nous vous contacterons pour confirmer votre rendez-vous.",
      formTitle: "Formulaire de Rendez-vous",
      name: "Nom complet",
      namePlaceholder: "Votre nom",
      email: "Email",
      emailPlaceholder: "votre@email.com",
      phone: "Téléphone",
      service: "Service souhaité",
      serviceSelect: "Sélectionnez un service",
      mode: "Mode de consultation *",
      presentiel: "En Cabinet",
      presentielSub: "Tel Aviv",
      visio: "En Visio",
      visioSub: "Zoom / Teams",
      date: "Date souhaitée",
      message: "Message",
      messagePlaceholder: "Décrivez brièvement votre besoin...",
      send: "Envoyer la Demande",
      sending: "Envoi en cours...",
      successTitle: "Merci !",
      success: "Votre demande de rendez-vous a bien été reçue. Nous vous contacterons dans les plus brefs délais.",
      newRdv: "Nouveau rendez-vous",
      infoTitle: "Informations",
      address: "Adresse",
      addressVal: "Tel Aviv, Israël",
      hours: "Horaires",
      hoursVal1: "Dimanche – Jeudi",
      hoursVal2: "9h00 – 18h00",
      chatTitle: "Chat Direct",
      chatDesc: "Besoin d'une réponse rapide ? Utilisez notre chat en direct en cliquant sur l'icône en bas à droite de votre écran.",
      chatAvailable: "Disponible maintenant",
    },
    chat: {
      title: "Assistant Virtuel",
      online: "En ligne",
      heading: "Chat Direct",
      intro: "Posez vos questions, nous vous répondrons rapidement.",
      namePlaceholder: "Votre nom",
      emailPlaceholder: "Votre email",
      start: "Démarrer la conversation",
      welcome: (name) => `Bonjour ${name} ! Bienvenue. Comment pouvons-nous vous aider aujourd'hui ?`,
      inputPlaceholder: "Tapez votre message...",
    },
    about: {
    label: "À propos",
    title: "Dr Ronit Kalfon",
    subtitle: "Docteur en Pharmacie · Nutrition Diététique · Luxopuncture",
    bio1: "Docteur en Pharmacie de formation, le Dr Ronit Kalfon a dédié sa carrière à l'articulation entre science pharmaceutique et équilibre métabolique. Son expertise unique en pharmacologie lui permet de concevoir des protocoles nutritionnels d'une précision clinique, intégrant les interactions biologiques et les besoins spécifiques de chaque patient.",
    bio2: "Installée au cœur de Tel Aviv, elle propose une approche globale rare et performante, alliant nutrition clinique, suivi diététique personnalisé et luxopuncture pour des résultats profonds et durables.",
    bio3: "Doctorat : Docteur en Pharmacie – Diplôme Universitaire International (Nutrition – Diététique) Hôpital BICHAT - Paris",
    stat1: "Docteur en Pharmacie",
    stat2: "Ans d'Expérience",
    stat3: "Patients Accompagnés",
    stat4: "Spécialisations",
    journeyTitle: "Parcours Professionnel",
    journeySubtitle: "Une exigence scientifique au service du soin.",
    approachTitle: "Mon Approche",
    approach1title: "La précision pharmaceutique au service de la nutrition.",
    approach1: "Mon parcours de Docteur en Pharmacie me confère une compréhension approfondie des mécanismes biologiques. Chaque protocole nutritionnel et diététique est élaboré avec rigueur.",
    approach2title: "La luxopuncture comme catalyseur.",
    approach2: "En synergie avec le suivi nutritionnel, la luxopuncture permet d'agir directement sur le système endocrinien pour réguler les hormones de la faim et du stress. Cette combinaison unique accélère la réponse de l'organisme et pérennise vos résultats sans frustration.",
    approach3title: "Un accompagnement humain et une disponibilité totale.",
    approach3: "Au-delà de la science, chaque patient est unique. J'accorde une importance fondamentale à l'écoute et à la flexibilité de mon suivi. Je vous reçois à la clinique Dental Harmonia et à Kikar Hamedina, assurant une continuité de service.",
    contactBtn: "Me Contacter",
    m1year: "Doctorat", m1title: "Docteur en Pharmacie", m1desc: "Formation approfondie en biochimie, pharmacologie et sciences du médicament.",
    m2year: "Spécialisation", m2title: "Nutrition Clinique", m2desc: "Expertise en nutrition clinique et protocoles diététiques personnalisés.",
    m3year: "Innovation", m3title: "Luxopuncture", m3desc: "Certification en techniques de biostimulation infrarouge et réflexothérapie.",
    m4year: "Aujourd'hui", m4title: "Clinique Tel Aviv", m4desc: "Expertise dédiée au bien-être global, disponible à la clinique Dental Harmonia et à Kikar Hamedina.",
    },
    footer: {
      bio: "Docteur en Pharmacie, spécialisée en nutrition, suivi diététique et luxopuncture. Une approche scientifique et personnalisée au cœur de Tel Aviv.",
      servicesTitle: "Services",
      s1: "Nutrition & Diététique", s2: "Luxopuncture", s3: "Arrêt du Tabac", s4: "Gestion du Poids",
      navTitle: "Navigation",
      rights: "Tous droits réservés.",
    },
    servicesPage: {
    s: [
      { title: "Expertise Nutritionnelle & Métabolique", subtitle: "Un protocole sur mesure, dicté par la biologie", description: "Grâce à son doctorat en pharmacie, le Dr Kalfon élabore des programmes d'une précision inégalée. Chaque protocole intègre votre profil biologique, vos éventuelles interactions médicamenteuses et vos besoins métaboliques spécifiques.", benefits: ["Bilan biologique approfondi et personnalisé", "Protocoles alimentaires adaptés à votre profil", "Suivi régulier et ajustements de précision", "Optimisation des apports essentiels ciblés", "Prise en compte des interactions médicamenteuses"] },
      { title: "Perte de Poids & Régulation Hormonale", subtitle: "Libérez-vous des compulsions alimentaires", description: "La luxopuncture stimule les points réflexes pour réguler les hormones de la faim (ghréline et leptine) et réduire les pulsions de manière naturelle. Associée à un suivi de précision, cette approche garantit une transformation durable du métabolisme.", benefits: ["Régulation naturelle des signaux de satiété", "Élimination des compulsions alimentaires", "Rééquilibrage profond du système endocrinien", "Planification nutritionnelle individualisée", "Suivi haute proximité pour des résultats pérennes"] },
      { title: "Arrêt du Tabac", subtitle: "Protocole de sevrage en douceur", description: "La luxopuncture stimule la production naturelle d'endorphines et de sérotonine pour neutraliser le manque physique et l'irritabilité. Un accompagnement clinique complet pour une libération définitive, sans les contraintes habituelles du sevrage.", benefits: ["Neutralisation rapide du besoin de fumer", "Élimination des symptômes liés au sevrage", "Relance naturelle de la production d'endorphines et sérotonines", "Gestion experte du stress post-arrêt", "Contrôle métabolique pour prévenir la prise de poids associée"] },
      { title: "Sommeil & Relaxation", subtitle: "Retrouvez un sommeil profond et réparateur", description: "En agissant sur les méridiens liés au cycle circadien, la luxopuncture aide à réguler naturellement les phases de repos et à réduire le cortisol, offrant une alternative scientifique aux solutions médicamenteuses.", benefits: ["Synchronisation du cycle circadien naturel", "Réduction du stress et de l'anxiété", "Optimisation de la qualité du sommeil profond", "Relâchement nerveux dès la première séance", "Alternative naturelle aux somnifères classiques"] },
      { title: "Rajeunissement du Visage (Lifting par Luxo)", subtitle: "Éclat naturel, sans injection", description: "La stimulation par rayonnement infrarouge réactive la synthèse naturelle de collagène et d'élastine. Un protocole non invasif de haute technologie qui restaure la structure et l'éclat de votre peau.", benefits: ["Stimulation du drainage et de la microcirculation", "Décongestion du visage", "Atténuation des cernes et des poches", "Luminosité du teint", "Tonification des muscles faciaux", "Stimulation des fibroblastes producteurs de collagène & d'élastine", "Élasticité, fermeté et tension de la peau", "Zéro injection, zéro traumatisme cutané"] },
      { title: "Gestion des Addictions & Pulsions", subtitle: "Rééquilibrage profond du système nerveux", description: "La luxopuncture offre un soutien majeur dans la libération des comportements compulsifs en stabilisant le système endocrinien et en favorisant la sécrétion naturelle de neurotransmetteurs du bien-être.", benefits: ["Restauration de l'équilibre endocrinien", "Soutien clinique au sevrage comportemental", "Optimisation des neurotransmetteurs (Sérotonine)", "Accompagnement exclusif et personnalisé", "Approche physiologique non médicamenteuse"] },
      { title: "Bien-être & Ménopause", subtitle: "Sérénité et équilibre hormonal", description: "La luxopuncture offre une réponse clinique aux bouleversements hormonaux de la ménopause. En régulant le système endocrinien, ce protocole atténue les inconforts physiques et émotionnels, tout en stabilisant le métabolisme pour une transition sereine.", benefits: ["Réduction significative des bouffées de chaleur et sudation", "Amélioration de l'humeur et de la qualité du sommeil", "Contrôle de la silhouette et de la rétention d'eau", "Accompagnement nutritionnel métabolique adapté", "Approche naturelle sans recours aux hormones de synthèse", "Fatigue et déprime"] },
    ],
    },
    servicesPreview: {
      s1title: "Nutrition Clinique", s1desc: "Programmes nutritionnels personnalisés fondés sur une analyse pharmaceutique précise de vos besoins.", s1note: "Protocole nutritionnel adapté à votre profil biologique",
      s7title: "Bien-être & Ménopause", s7desc: "Traverser cette transition hormonale avec confort et vitalité. Protocole spécifique pour atténuer les bouffées de chaleur, réguler l'humeur et préserver la silhouette.", s7note: "Protocole hormonal naturel sans synthèse",
      s2title: "Perte de Poids & Équilibre Métabolique", s2desc: "Libérez-vous des compulsions alimentaires grâce à la synergie de la luxopuncture et d'un protocole nutritionnel de précision. Stimulation ciblée des points réflexes endocriniens pour réguler naturellement les hormones de la faim.", s2note: "Stimulation des points réflexes endocriniens",
      s3title: "Arrêt du Tabac", s3desc: "Un sevrage tabagique serein, soutenu par une approche neuro-biologique. La luxopuncture agit sur les récepteurs de dopamine et sérotonine pour neutraliser le manque physique.", s3note: "Action sur les récepteurs de dopamine et sérotonine",
      s4title: "Sommeil & Relaxation", s4desc: "Retrouver un sommeil réparateur et une sérénité profonde. Stimulation naturelle de la sérotonine et mélatonine pour libérer les tensions nerveuses.", s4note: "Régulation du cycle circadien",
      s5title: "Rajeunissement du Visage (Lifting par Luxo)", s5desc: "Un soin anti-âge non invasif : stimulation de la micro-circulation et de la production de collagène et d'élastine. Raffermit les tissus, lisse les traits, redonne de la luminosité.", s5note: "Activation cellulaire non invasive",
      s6title: "Dépendances et addictions", s6desc: "Un accompagnement global pour rompre les comportements addictifs. Action réflexe sur le système limbique pour stabiliser l'état émotionnel et réduire l'anxiété liée au sevrage.", s6note: "Rééquilibrage du système endocrinien",
    },
    luxo: {
      heroBadge: "Technologie Réflexe Infrarouge",
      heroTitle1: "La Luxopuncture®",
      heroTitle2: "L'Innovation par la Lumière",
      heroDesc: "Technologie réflexe par rayonnement infrarouge, non invasive et indolore, elle s'inscrit dans la lignée des techniques de stimulation neuro-sensorielle. Elle restaure l'équilibre fonctionnel de l'organisme en agissant avec précision sur les systèmes hormonal, digestif et lymphatique.",
      howBadge: "Mode d'action",
      howTitle: "Comment fonctionne la Luxopuncture® ?",
      howP1: "L'énergie du rayonnement infrarouge est transmise aux terminaisons nerveuses constituant le point réflexe. Cette biostimulation active le <strong>système nerveux végétatif</strong>, visant à rétablir l'équilibre du système endocrinien.",
      howP2: "Deux centres régulateurs majeurs sont ciblés : <strong>l'hypothalamus et l'hypophyse</strong>. Situés au cœur du cerveau, ils gouvernent le système nerveux autonome, la sécrétion des neuro-hormones et les fonctions comportementales (appétit, dépendances, stress, cycles veille-sommeil…).",
      howP3: "Les soins se déroulent à raison d'<strong>une séance de 30 minutes par semaine</strong>, durant laquelle une trentaine de points stratégiques sont stimulés. Cette technique est douce, indolore, sécuritaire, non invasive et sans aucun risque médical.",
      hormonesBadge: "Mécanisme hormonal",
      hormonesTitle: "4 Hormones Essentielles Rééquilibrées",
      hormonesDesc: "Ces quatre neurotransmetteurs sont les piliers de nos ressentis et de nos comportements. La Luxopuncture® contribue naturellement à leur rééquilibrage.",
      h1name: "Endorphine", h1sub: "L'hormone de la sérénité", h1desc: "Procure un sentiment de plénitude et possède une action antalgique naturelle. Un déficit peut générer nervosité et irritabilité.",
      h2name: "Dopamine", h2sub: "L'hormone du plaisir", h2desc: "Sa carence est associée à une baisse de motivation. Elle régule l'envie irrépressible de consommer des aliments gras, sucrés ou de fumer.",
      h3name: "Sérotonine", h3sub: "L'hormone de la satiété", h3desc: "Véritable antidépresseur naturel, elle régule l'appétit. Un taux optimal permet d'éviter les grignotages compulsifs et la prise de poids.",
      h4name: "Mélatonine", h4sub: "L'hormone du sommeil", h4desc: "Synthétisée à partir de la sérotonine, elle cadence notre horloge biologique. Sa régulation facilite l'endormissement et réduit l'anxiété.",
      benefitsTitle: "Pourquoi Choisir la Luxopuncture® ?",
      b1title: "Non Invasif", b1desc: "Aucune aiguille. Un faisceau infrarouge indolore stimule les points réflexes.",
      b2title: "Sans Effets Secondaires", b2desc: "Technique naturelle, sans recours aux substances chimiques, ni médicaments.",
      b3title: "Séances de 30 min", b3desc: "Un protocole hebdomadaire rapide, pour des résultats progressifs et pérennes.",
      b4title: "Polyvalence", b4desc: "Poids, tabac, addictions, sommeil, stress, ménopause, rajeunissement — une réponse globale.",
      b5title: "Équilibre Biologique", b5desc: "Harmonise naturellement la production de vos neurotransmetteurs essentiels (endorphine, dopamine, sérotonine, mélatonine).",
      b6title: "Fondement Scientifique", b6desc: "Basée sur la réflexothérapie et la stimulation du système nerveux central (hypothalamus – hypophyse).",
      indicationsTitle: "Indications principales",
      indicationsDesc: "La Luxopuncture® est particulièrement indiquée pour rééquilibrer l'organisme et traiter :",
      i1: "Perte de poids et stabilisation métabolique",
      i2: "Sevrage tabagique et gestion des dépendances (tabac, alcool…)",
      i3: "Relaxation profonde et contrôle du stress chronique",
      i4: "Amélioration de l'architecture du sommeil",
      i5: "Rajeunissement facial naturel et relance lymphatique",
      i6: "Troubles de la ménopause (bouffées de chaleur, humeur)",
      i7: "Troubles du transit",
      i8: "Migraines",
      faqBadge: "Questions fréquentes",
      faqTitle: "Tout savoir sur la Luxopuncture®",
      faq1q: "Quelle différence avec l'acupuncture ou la digitopuncture ?", faq1a: "Bien que ces 3 techniques soient basées sur la stimulation de points réflexes et d'auriculothérapie, leur méthode d'action diffère. Contrairement à l'acupuncture qui utilise des aiguilles, ou à la digitopuncture qui repose sur la pression manuelle, la luxopuncture utilise un rayonnement infrarouge. Cette technologie permet une stimulation des points sans douleur et sans risque d'infection. En tant que pharmacienne, je privilégie cette approche pour sa précision millimétrée, sa sécurité totale et son absence de caractère invasif.",
      faq2q: "Les résultats sont-ils durables dans le temps ?", faq2a: "Oui, l'objectif de la luxopuncture est de rétablir un équilibre biologique profond et durable. En stabilisant vos cycles hormonaux sur plusieurs semaines, les résultats s'ancrent naturellement dans votre métabolisme. Pour pérenniser ces bénéfices, des séances d'entretien ponctuelles peuvent être programmées.",
      faq3q: "À partir de quel âge peut-on pratiquer la Luxopuncture® ?", faq3a: "Les soins peuvent être pratiqués sur les enfants et les adolescents. Pour l'amincissement des jeunes en phase de croissance, le suivi alimentaire doit se faire sous contrôle médical.",
      faq4q: "Peut-on interrompre les soins durant les vacances ?", faq4a: "Les cures d'amincissement, de relaxation et de visage peuvent être interrompues. Pour le sevrage tabagique (cure sur 3 à 5 jours consécutifs), il vaut mieux éviter toute interruption.",
      faq5q: "Y a-t-il des contre-indications médicales ?", faq5a: "Par principe de précaution, les cures sont déconseillées aux femmes enceintes, aux personnes atteintes de maladies graves ou de troubles épileptiques. L'amincissement chez les enfants en croissance nécessite une surveillance médicale.",
      faq6q: "Existe-t-il des études validant l'efficacité de la Luxopuncture® ?", faq6a: "Absolument. L'efficacité de la luxopuncture a été démontrée par des études cliniques rigoureuses, notamment une étude menée par un organisme indépendant (TEREO International) sur un échantillon de 291 personnes. Les résultats attestent de taux de satisfaction très élevés, atteignant 95% pour l'arrêt du tabac et plus de 90% pour la gestion du poids.",
      ctaTitle: "Essayez la Luxopuncture®",
      ctaDesc: "Prenez rendez-vous pour votre première séance et découvrez les bienfaits de cette technique innovante, guidée par l'expertise de Dr. Ronit Kalfon.",
      ctaBtn: "Réserver une Séance",
    },
  },
  en: {
    nav: {
      home: "Home",
      services: "Services",
      luxopuncture: "Luxopuncture",
      about: "About",
      contact: "Contact",
      rdv: "Book Appointment",
      pricing: "Pricing",
    },
    hero: {
      badge: "Doctor of Pharmacy",
      title1: "Restore Balance",
      title2: "& Natural Well-being",
      subtitle: "Clinical nutrition, personalized dietary follow-up and luxopuncture. A unique approach based on pharmaceutical expertise, in the heart of Tel Aviv.",
      cta: "Book an Appointment",
      services: "Discover Services",
      certified: "Certified practitioner",
      centre: "Luxomed Approved Centre",
      stat1: "Years of experience",
      stat2: "Private clinic",
      stat3: "Trained",
      stat3label: "In France",
      luxoCardDesc: "Non-invasive infrared light technique for global well-being",
    },
    services: {
      badge: "Care ecosystem",
      title: "Your Goals, Our Expertise",
      subtitle: "Each treatment is designed with the rigor of a doctor of pharmacy and the gentleness of a holistic approach.",
      more: "View all services",
      pageTitle: "Excellence in the Service of Your Health",
      pageSubtitle: "A complete range of care, from clinical nutrition to luxopuncture, designed with the rigor of a doctor of pharmacy.",
      pageLabel: "Our Services",
      cta: "Ready to Start?",
      ctaDesc: "Every journey begins with a first consultation. Book an appointment to discover the program tailored to your needs.",
      ctaBtn: "Book My Consultation",
      rdvBtn: "Book an Appointment",
    },
    process: {
      badge: "Care protocol",
      title: "How does a follow-up work?",
      subtitle: "Personalized support, step by step, to help you achieve your goals sustainably.",
      step: "Step",
      s1title: "In-depth Analysis",
      s1desc: "Comprehensive assessment integrating your medical history, eating habits and personal goals.",
      s1detail: "Biological tests and pharmaceutical anamnesis",
      s2title: "Molecular Balance",
      s2desc: "Development of a precise nutritional protocol, enriched by clinical pharmacology expertise.",
      s2detail: "Micro and macronutrients precisely dosed",
      s3title: "Luxopuncture®",
      s3desc: "Targeted luxopuncture sessions to stimulate reflex points and rebalance the endocrine system.",
      s3detail: "Non-invasive infrared on meridians",
      s4title: "Lasting Vitality",
      s4desc: "Continuous monitoring and adjustments to ensure lasting results and daily well-being.",
      s4detail: "Follow-up consultations and reassessment",
    },
    clinic: {
      badge: "Our space",
      title: "A Medical Practice in the Heart of Tel Aviv",
      desc: "In a calm and confidential setting, Dr. Kalfon receives patients by appointment for in-depth consultations. Each care is individualized, respecting medical confidentiality and patient comfort.",
      f1title: "Individualized Medical Follow-up",
      f1desc: "Each consultation is tailored to your profile, history and objectives",
      f2title: "Appointment-based Practice",
      f2desc: "Located in the heart of Tel Aviv, accessible and confidential",
      f3title: "Soothing Environment",
      f3desc: "A space designed for serenity and quality of care",
    },
    cta: {
      title1: "Start Your Transformation",
      title2: "Today",
      subtitle: "Book your first consultation and discover how the alliance of science and innovation can transform your well-being.",
      btn: "Book an Appointment",
    },
    contact: {
      serviceOptions: [
        { value: "nutrition", label: "Nutrition & Dietary Follow-up" },
        { value: "luxopuncture_weight", label: "Luxopuncture — Weight Loss" },
        { value: "luxopuncture_smoking", label: "Luxopuncture — Stop Smoking" },
        { value: "luxopuncture_addiction", label: "Luxopuncture — Addictions" },
        { value: "luxopuncture_sleep", label: "Luxopuncture — Sleep" },
        { value: "luxopuncture_relaxation", label: "Luxopuncture — Relaxation" },
        { value: "luxopuncture_rejuvenation", label: "Luxopuncture — Facial Rejuvenation" },
      ],
      label: "Contact",
      title: "Book an Appointment",
      pageSubtitle: "Contact us to schedule your first consultation or for any questions about our services.",
      subtitle: "Fill in the form below and we will contact you to confirm your appointment.",
      formTitle: "Appointment Form",
      name: "Full name",
      namePlaceholder: "Your name",
      email: "Email",
      emailPlaceholder: "your@email.com",
      phone: "Phone",
      service: "Desired service",
      serviceSelect: "Select a service",
      mode: "Consultation mode *",
      presentiel: "In Person",
      presentielSub: "Tel Aviv",
      visio: "Video Call",
      visioSub: "Zoom / Teams",
      date: "Preferred date",
      message: "Message",
      messagePlaceholder: "Briefly describe your need...",
      send: "Send Request",
      sending: "Sending...",
      successTitle: "Thank you!",
      success: "Your appointment request has been received. We will contact you as soon as possible.",
      newRdv: "New appointment",
      infoTitle: "Information",
      address: "Address",
      addressVal: "Tel Aviv, Israel",
      hours: "Hours",
      hoursVal1: "Sunday – Thursday",
      hoursVal2: "9:00 – 18:00",
      chatTitle: "Live Chat",
      chatDesc: "Need a quick answer? Use our live chat by clicking the icon at the bottom right of your screen.",
      chatAvailable: "Available now",
    },
    chat: {
      title: "Virtual Assistant",
      online: "Online",
      heading: "Live Chat",
      intro: "Ask your questions, we'll reply quickly.",
      namePlaceholder: "Your name",
      emailPlaceholder: "Your email",
      start: "Start conversation",
      welcome: (name) => `Hello ${name}! Welcome. How can we help you today?`,
      inputPlaceholder: "Type your message...",
    },
    about: {
      label: "About",
      title: "Dr. Ronit Kalfon",
      subtitle: "Doctor of Pharmacy · Nutrition · Luxopuncture",
      bio1: "Trained as a doctor of pharmacy, Dr. Ronit Kalfon has dedicated her career to the intersection of pharmaceutical science and holistic well-being.",
      bio2: "Her unique expertise in pharmacology allows her to offer nutritional prescriptions of exceptional precision, taking into account every interaction and biological need of her patients.",
      bio3: "Based in the heart of Tel Aviv, she supports her patients with a global approach combining clinical nutrition, personalized dietary follow-up, and luxopuncture — a rare and particularly effective combination.",
      stat1: "Doctor of Pharmacy",
      stat2: "Years of Experience",
      stat3: "Patients Supported",
      stat4: "Specializations",
      journeyTitle: "Professional Journey",
      journeySubtitle: "A path guided by scientific rigor and a passion for care.",
      approachTitle: "My Approach",
      approach1title: "Pharmaceutical precision in the service of nutrition.",
      approach1: "My background as a doctor of pharmacy gives me a deep understanding of biological mechanisms. Each nutritional prescription is developed with the same rigor as a medical prescription.",
      approach2title: "Luxopuncture as a catalyst.",
      approach2: "In addition to nutritional follow-up, luxopuncture acts directly on the endocrine system, accelerating and sustaining results.",
      approach3title: "A human approach.",
      approach3: "Beyond science, every patient is unique. I place fundamental importance on listening and adapting each protocol.",
      contactBtn: "Contact Me",
      m1year: "Doctorate", m1title: "Doctor of Pharmacy", m1desc: "In-depth training in pharmacology, biochemistry and pharmaceutical sciences.",
      m2year: "Specialization", m2title: "Clinical Nutrition", m2desc: "Expertise in micronutrition and personalized dietary follow-up.",
      m3year: "Innovation", m3title: "Luxopuncture", m3desc: "Training and certification in reflex light therapy techniques.",
      m4year: "Today", m4title: "Tel Aviv Clinic", m4desc: "Practice dedicated to global well-being, in the heart of Tel Aviv.",
    },
    footer: {
      bio: "Doctor of Pharmacy, specialized in nutrition, dietary follow-up and luxopuncture. A scientific and personalized approach in the heart of Tel Aviv.",
      servicesTitle: "Services",
      s1: "Nutrition & Dietetics", s2: "Luxopuncture", s3: "Stop Smoking", s4: "Weight Management",
      navTitle: "Navigation",
      rights: "All rights reserved.",
    },
    servicesPage: {
      s: [
        { title: "Clinical Nutrition & Dietary Follow-up", subtitle: "A tailored program, guided by science", description: "Thanks to her doctorate in pharmacy, Dr. Kalfon develops nutritional programs of unparalleled precision. Each prescription takes into account your complete biological profile, drug interactions and specific physiological needs.", benefits: ["In-depth and personalized nutritional assessment", "Dietary plans adapted to your medical profile", "Regular follow-up and dynamic adjustments", "Targeted nutritional supplementation", "Consideration of drug interactions"] },
        { title: "Weight Loss", subtitle: "Free yourself from food compulsions", description: "Luxopuncture acts on the reflex points of the endocrine system to naturally reduce food compulsions. Combined with rigorous dietary follow-up, this approach offers lasting results.", benefits: ["Natural appetite reduction", "Reduction of food compulsions", "Endocrine hormonal rebalancing", "Personalized dietary program", "Long-term follow-up for lasting results"] },
        { title: "Stop Smoking", subtitle: "Gentle withdrawal protocol", description: "Luxopuncture stimulates the production of natural endorphins, significantly reducing withdrawal symptoms and cravings. Comprehensive support for definitive freedom.", benefits: ["Rapid reduction of smoking cravings", "Attenuation of withdrawal symptoms", "Natural stimulation of endorphins", "Post-cessation stress management", "Prevention of associated weight gain"] },
        { title: "Sleep & Relaxation", subtitle: "Rediscover restful sleep", description: "By acting on the meridians linked to the circadian cycle, luxopuncture helps naturally regulate sleep and reduce chronic stress, without recourse to medication.", benefits: ["Regulation of the circadian cycle", "Reduction of stress and anxiety", "Improvement of sleep quality", "Deep relaxation from the first session", "Natural alternative to sleeping pills"] },
        { title: "Facial Rejuvenation", subtitle: "Natural radiance, without injection", description: "Infrared light stimulation naturally activates the production of collagen and elastin. A non-invasive treatment that reveals the radiance of your skin.", benefits: ["Natural collagen stimulation", "Improvement of complexion and radiance", "Reduction of fine lines", "Visible skin firming", "Zero injection, zero pain"] },
        { title: "Addiction Management", subtitle: "Deep rebalancing of the nervous system", description: "Luxopuncture offers valuable support in managing addictive behaviors by rebalancing the endocrine system and promoting the natural production of neurotransmitters.", benefits: ["Rebalancing of the endocrine system", "Support for behavioral withdrawal", "Stimulation of well-being neurotransmitters", "Comprehensive and personalized support", "Non-medicinal approach"] },
        { title: "Well-being & Menopause", subtitle: "Serenity and hormonal balance", description: "Luxopuncture offers a clinical response to the hormonal upheavals of menopause. By regulating the endocrine system, this protocol alleviates physical and emotional discomfort while stabilizing metabolism for a peaceful transition.", benefits: ["Significant reduction of hot flashes and sweating", "Improvement of mood and sleep quality", "Control of figure and water retention", "Adapted metabolic nutritional support", "Natural approach without synthetic hormones", "Fatigue and low mood"] },
      ],
    },
    servicesPreview: {
      s1title: "Clinical Nutrition", s1desc: "Personalized nutritional programs based on precise pharmaceutical analysis of your needs.", s1note: "Prescription adapted to your biological profile",
      s7title: "Well-being & Menopause", s7desc: "Navigate this hormonal transition with comfort and vitality. A specific protocol to reduce hot flashes, regulate mood and preserve your figure.", s7note: "Natural hormonal protocol",
      s2title: "Weight Loss", s2desc: "Reduction of food compulsions through luxopuncture and tailored dietary follow-up.", s2note: "Stimulation of endocrine reflex points",
      s3title: "Stop Smoking", s3desc: "Smoking cessation protocol combining luxopuncture and personalized support.", s3note: "Action on dependency receptors",
      s4title: "Sleep & Relaxation", s4desc: "Improving sleep quality and stress management through infrared stimulation.", s4note: "Regulation of circadian cycle",
      s5title: "Facial Rejuvenation", s5desc: "Natural stimulation of collagen and elastin production through light.", s5note: "Non-invasive cellular activation",
      s6title: "Addictions", s6desc: "Management of addictive behaviors through luxopuncture and comprehensive follow-up.", s6note: "Rebalancing the endocrine system",
    },
    luxo: {
      heroBadge: "Infrared Reflex Technology",
      heroTitle1: "Luxopuncture®",
      heroTitle2: "Innovation Through Light",
      heroDesc: "Infrared reflex technology, non-invasive and painless, in line with ancestral energy techniques. It restores the functional balance of the body by acting on the hormonal, digestive and lymphatic systems.",
      howBadge: "Mode of action",
      howTitle: "How does Luxopuncture® work?",
      howP1: "The energy of infrared radiation is transferred to the nerve endings that form the reflex point. This stimulation acts on the <strong>autonomic nervous system</strong>, aiming to restore the functional balance of the hormonal system.",
      howP2: "Two key organs are targeted: <strong>the hypothalamus and the pituitary gland</strong>, located in the brain, which regulate the autonomic nervous system, neurohormone secretion and behavioral functions (eating, addictions, stress, sleep-wake cycles…).",
      howP3: "Sessions take place at a rate of <strong>one 30-minute session per week</strong>, during which about thirty points are stimulated. The technique is gentle, painless, non-invasive and risk-free.",
      hormonesBadge: "Hormonal mechanism",
      hormonesTitle: "4 Essential Hormones Rebalanced",
      hormonesDesc: "These four hormones play an essential role in our feelings, mood swings and behaviors. Luxopuncture® naturally contributes to their rebalancing.",
      h1name: "Endorphin", h1sub: "The well-being hormone", h1desc: "Released during physical effort, it provides a feeling of well-being and fulfillment. It also has an analgesic effect. A deficiency can generate nervousness and irritability.",
      h2name: "Dopamine", h2sub: "The pleasure hormone", h2desc: "A dopamine deficiency is associated with disinterest in life, even depression. It would also increase the irresistible urge to consume sweet or fatty foods, to smoke…",
      h3name: "Serotonin", h3sub: "The happiness hormone", h3desc: "It has an anti-depressant effect and regulates the feeling of satiety. An optimal level avoids attraction to sugar. A deficiency promotes compulsive snacking and weight gain.",
      h4name: "Melatonin", h4sub: "The sleep hormone", h4desc: "Synthesized from serotonin, it regulates our biological clock. When deficient, falling asleep is difficult, sleep is disturbed, with a risk of anxiety and addictions.",
      benefitsTitle: "Why Choose Luxopuncture®?",
      b1title: "Non-Invasive", b1desc: "No needles, no pain. A painless infrared beam stimulates reflex points.",
      b2title: "No Side Effects", b2desc: "Natural technique, without chemical substances or medications.",
      b3title: "30-min Sessions", b3desc: "One session per week, about thirty points stimulated, progressive and lasting results.",
      b4title: "Versatile", b4desc: "Addictions, weight, sleep, stress, menopause, rejuvenation — one protocol.",
      b5title: "Global Well-being", b5desc: "Naturally rebalances endorphins, dopamine, serotonin and melatonin.",
      b6title: "Scientifically Based", b6desc: "Based on reflexotherapy and stimulation of the autonomic nervous system (hypothalamus / pituitary).",
      indicationsTitle: "Indications",
      indicationsDesc: "Luxopuncture® is particularly effective for rebalancing the body and:",
      i1: "Weight loss and reduction of food compulsions",
      i2: "Smoking cessation and addiction management (tobacco, alcohol…)",
      i3: "Deep relaxation and chronic stress management",
      i4: "Improving sleep quality",
      i5: "Natural facial rejuvenation (face skin, light legs)",
      i6: "Menopause-related disorders",
      i7: "Anxiety and mood disorders",
      i8: "Eating behavior disorders",
      faqBadge: "Frequently asked questions",
      faqTitle: "Everything about Luxopuncture®",
      faq1q: "What is the difference with acupuncture and digitopuncture?", faq1a: "All 3 techniques are based on stimulating reflex points and auriculotherapy. Luxopuncture® uses a painless infrared beam. Acupuncture is a medical procedure with needles. Digitopuncture uses mechanical pressure from a finger or stylus.",
      faq2q: "Do the effects last over time?", faq2a: "Yes, the effects last very well over time. If needed, maintenance sessions can be done after the initial treatment.",
      faq3q: "From what age can Luxopuncture® be practiced?", faq3a: "Care can be provided to children and adolescents. For weight loss in young people in the growth phase, dietary follow-up must be done under medical supervision.",
      faq4q: "Can a treatment be interrupted during vacation?", faq4a: "Slimming, relaxation and facial treatments can be interrupted. For smoking cessation (3 to 5 consecutive days), it is best to avoid any interruption.",
      faq5q: "Are there contraindications?", faq5a: "As a precaution, treatments are not recommended for pregnant women, people with serious illnesses or epileptic disorders. Weight loss in growing children requires medical supervision.",
      faq6q: "Are there scientific studies on Luxopuncture®?", faq6a: "Yes. Clinical studies have been conducted, including an independent clinical evaluation (Dr Vaillant) and a study on pre-menopause symptoms. These works demonstrate the effectiveness and tolerance of the technique.",
      ctaTitle: "Try Luxopuncture®",
      ctaDesc: "Book your first session and discover the benefits of this innovative technique, guided by the expertise of Dr. Ronit Kalfon.",
      ctaBtn: "Book a Session",
    },
  },
  he: {
    nav: {
      home: "בית",
      services: "שירותים",
      luxopuncture: "לוקסופונקטורה",
      about: "אודות",
      contact: "צור קשר",
      rdv: "קביעת תור",
      pricing: "תמחור",
    },
    hero: {
      badge: "דוקטור לפרמקולוגיה",
      title1: "מצאו מחדש את האיזון",
      title2: "ורווחה טבעית",
      subtitle: "תזונה קלינית, ליווי תזונתי אישי ולוקסופונקטורה. גישה ייחודית המבוססת על מומחיות פרמצויטית, בלב תל אביב.",
      cta: "קביעת תור",
      services: "גלו את השירותים",
      certified: "מטפלת מוסמכת",
      centre: "מרכז מוסמך לוקסומד",
      stat1: "שנות ניסיון",
      stat2: "קליניקה פרטית",
      stat3: "הוסמכה",
      stat3label: "בצרפת",
      luxoCardDesc: "טכניקת אור אינפרא-אדום לא פולשנית לרווחה כוללת",
    },
    services: {
      badge: "מערכת טיפולים",
      title: "המטרות שלכם, המומחיות שלנו",
      subtitle: "כל טיפול מתוכנן עם הקפדה של דוקטור לפרמקולוגיה ועדינות של גישה הוליסטית.",
      more: "לכל השירותים",
      pageTitle: "מצוינות בשירות בריאותכם",
      pageSubtitle: "מגוון מלא של טיפולים, מתזונה קלינית ועד לוקסופונקטורה, מתוכנן בדקדקנות של דוקטור לפרמקולוגיה.",
      pageLabel: "השירותים שלנו",
      cta: "מוכנים להתחיל?",
      ctaDesc: "כל מסע מתחיל בייעוץ ראשון. קבעו תור לגלות את התוכנית המותאמת לצרכיכם.",
      ctaBtn: "הזמנת ייעוץ",
      rdvBtn: "קביעת תור",
    },
    process: {
      badge: "פרוטוקול טיפול",
      title: "כיצד מתנהל מעקב?",
      subtitle: "ליווי אישי, צעד אחר צעד, לעזור לכם להשיג את מטרותיכם לאורך זמן.",
      step: "שלב",
      s1title: "ניתוח מעמיק",
      s1desc: "הערכה מקיפה הכוללת את ההיסטוריה הרפואית שלכם, הרגלי האכילה והמטרות האישיות.",
      s1detail: "בדיקות ביולוגיות ואנמנזה פרמצויטית",
      s2title: "איזון מולקולרי",
      s2desc: "פיתוח פרוטוקול תזונתי מדויק, מועשר על ידי מומחיות בפרמקולוגיה קלינית.",
      s2detail: "מיקרו ומקרו-נוטריאנטים במינון מדויק",
      s3title: "לוקסופונקטורה®",
      s3desc: "טיפולים ממוקדים לגירוי נקודות לחץ בגוף ושיקום האיזון ההורמונלי.",
      s3detail: "קרן אור עדינה על נקודות הגוף — ללא מחטים וללא כאב",
      s4title: "חיוניות מתמשכת",
      s4desc: "מעקב רציף והתאמות להבטחת תוצאות ארוכות טווח ורווחה יומיומית.",
      s4detail: "ייעוצי מעקב והערכה מחדש",
    },
    clinic: {
      badge: "המרחב שלנו",
      title: "קליניקה רפואית בלב תל אביב",
      desc: "בסביבה שקטה וסודית, ד\"ר קלפון מקבלת מטופלים בתיאום מראש לייעוצים מעמיקים. כל טיפול מותאם אישית, תוך כיבוד סודיות רפואית ונוחות המטופל.",
      f1title: "מעקב רפואי אישי",
      f1desc: "כל ייעוץ מותאם לפרופיל, ההיסטוריה והמטרות שלכם",
      f2title: "קליניקה בתיאום מראש",
      f2desc: "בלב תל אביב, נגישה וסודית",
      f3title: "סביבה מרגיעה",
      f3desc: "מרחב המיועד לשלווה ואיכות הטיפול",
    },
    cta: {
      title1: "התחילו את השינוי",
      title2: "היום",
      subtitle: "קבעו את הייעוץ הראשון וגלו כיצד שילוב המדע והחדשנות יכול לשנות את רווחתכם.",
      btn: "קביעת תור",
    },
    contact: {
      serviceOptions: [
        { value: "nutrition", label: "תזונה וליווי תזונתי" },
        { value: "luxopuncture_weight", label: "לוקסופונקטורה — ירידה במשקל" },
        { value: "luxopuncture_smoking", label: "לוקסופונקטורה — גמילה מעישון" },
        { value: "luxopuncture_addiction", label: "לוקסופונקטורה — התמכרויות" },
        { value: "luxopuncture_sleep", label: "לוקסופונקטורה — שינה" },
        { value: "luxopuncture_relaxation", label: "לוקסופונקטורה — רלקסציה" },
        { value: "luxopuncture_rejuvenation", label: "לוקסופונקטורה — התחדשות פנים" },
      ],
      label: "צור קשר",
      title: "קביעת תור",
      pageSubtitle: "צרו קשר לתיאום הייעוץ הראשון שלכם או לכל שאלה על השירותים שלנו.",
      subtitle: "מלאו את הטופס ונחזור אליכם לאישור הפגישה.",
      formTitle: "טופס קביעת תור",
      name: "שם מלא",
      namePlaceholder: "שמכם",
      email: "אימייל",
      emailPlaceholder: "your@email.com",
      phone: "טלפון",
      service: "שירות מבוקש",
      serviceSelect: "בחרו שירות",
      mode: "אופן הייעוץ *",
      presentiel: "פיזי",
      presentielSub: "תל אביב",
      visio: "וידאו",
      visioSub: "Zoom / Teams",
      date: "תאריך מועדף",
      message: "הודעה",
      messagePlaceholder: "תארו בקצרה את הצורך שלכם...",
      send: "שליחת הבקשה",
      sending: "שולח...",
      successTitle: "תודה!",
      success: "בקשת התור התקבלה. ניצור איתכם קשר בהקדם.",
      newRdv: "תור חדש",
      infoTitle: "פרטי יצירת קשר",
      address: "כתובת",
      addressVal: "תל אביב, ישראל",
      hours: "שעות פעילות",
      hoursVal1: "ראשון – חמישי",
      hoursVal2: "9:00 – 18:00",
      chatTitle: "צ'אט ישיר",
      chatDesc: "צריכים מענה מהיר? השתמשו בצ'אט החי על ידי לחיצה על הסמל בפינה הימנית התחתונה.",
      chatAvailable: "זמין עכשיו",
    },
    chat: {
      title: "עוזר וירטואלי",
      online: "מקוון",
      heading: "צ'אט ישיר",
      intro: "שאלו את שאלותיכם, נענה במהירות.",
      namePlaceholder: "שמכם",
      emailPlaceholder: "האימייל שלכם",
      start: "התחלת שיחה",
      welcome: (name) => `שלום ${name}! ברוכים הבאים. כיצד נוכל לעזור לכם היום?`,
      inputPlaceholder: "הקלידו את הודעתכם...",
    },
    about: {
      label: "אודות",
      title: "ד\"ר רונית קלפון",
      subtitle: "דוקטור לפרמקולוגיה · תזונה · לוקסופונקטורה",
      bio1: "ד\"ר רונית קלפון, בעלת תואר דוקטור בפרמקולוגיה, הקדישה את קריירתה לצומת שבין המדע הפרמצויטי לבין הרווחה ההוליסטית.",
      bio2: "המומחיות הייחודית שלה בפרמקולוגיה מאפשרת לה להציע מרשמים תזונתיים בדיוק יוצא דופן, תוך התחשבות בכל האינטראקציות והצרכים הביולוגיים של מטופליה.",
      bio3: "מתבססת בלב תל אביב, היא מלווה את מטופליה בגישה כוללת המשלבת תזונה קלינית, ליווי תזונתי אישי ולוקסופונקטורה — שילוב נדיר ויעיל במיוחד.",
      stat1: "דוקטור לפרמקולוגיה",
      stat2: "שנות ניסיון",
      stat3: "מטופלים שולוו",
      stat4: "התמחויות",
      journeyTitle: "מסלול מקצועי",
      journeySubtitle: "מסע המונחה על ידי דקדקנות מדעית ותשוקה לטיפול.",
      approachTitle: "הגישה שלי",
      approach1title: "דיוק פרמצויטי בשירות התזונה.",
      approach1: "הרקע שלי כדוקטור לפרמקולוגיה מעניק לי הבנה עמוקה של המנגנונים הביולוגיים. כל מרשם תזונתי מפותח באותה דקדקנות כמו מרשם רפואי.",
      approach2title: "לוקסופונקטורה כמניע.",
      approach2: "בנוסף לליווי התזונתי, הלוקסופונקטורה פועלת ישירות על המערכת האנדוקרינית, מאיצה ומייצבת את התוצאות.",
      approach3title: "ליווי אנושי.",
      approach3: "מעבר למדע, כל מטופל הוא ייחודי. אני מייחסת חשיבות עליונה להקשבה ולהתאמת כל פרוטוקול.",
      contactBtn: "צרו קשר",
      m1year: "דוקטורט", m1title: "דוקטור לפרמקולוגיה", m1desc: "הכשרה מעמיקה בפרמקולוגיה, ביוכימיה ומדעי התרופות.",
      m2year: "התמחות", m2title: "תזונה קלינית", m2desc: "מומחיות במיקרונוטריציה וליווי תזונתי אישי.",
      m3year: "חדשנות", m3title: "לוקסופונקטורה", m3desc: "הכשרה והסמכה בטכניקות רפלקסולוגיה באור אינפרא-אדום.",
      m4year: "היום", m4title: "קליניקה בתל אביב", m4desc: "מרפאה המוקדשת לרווחה כוללת, בלב תל אביב.",
    },
    footer: {
      bio: "דוקטור לפרמקולוגיה, מתמחה בתזונה, ליווי תזונתי ולוקסופונקטורה. גישה מדעית ואישית בלב תל אביב.",
      servicesTitle: "שירותים",
      s1: "תזונה וכדיאטטיקה", s2: "לוקסופונקטורה", s3: "גמילה מעישון", s4: "ניהול משקל",
      navTitle: "ניווט",
      rights: "כל הזכויות שמורות.",
    },
    servicesPage: {
      s: [
        { title: "תזונה קלינית וליווי תזונתי", subtitle: "תוכנית אישית המבוססת על מדע", description: "בזכות הדוקטורט שלה בפרמקולוגיה, ד\"ר קלפון מפתחת תוכניות תזונה בדיוק ללא תחרות. כל מרשם מתחשב בפרופיל הביולוגי המלא שלכם, באינטראקציות התרופתיות ובצרכים הפיזיולוגיים הספציפיים שלכם.", benefits: ["הערכה תזונתית מעמיקה ואישית", "תוכניות תזונה מותאמות לפרופיל הרפואי שלכם", "מעקב סדיר והתאמות דינמיות", "תוספת תזונתית ממוקדת", "התחשבות באינטראקציות תרופתיות"] },
        { title: "ירידה במשקל", subtitle: "השתחררו מכפייתיות האכילה", description: "הלוקסופונקטורה פועלת על נקודות הרפלקס של המערכת האנדוקרינית כדי להפחית באופן טבעי את כפייתיות האכילה. בשילוב ליווי תזונתי קפדני, גישה זו מציעה תוצאות מתמשכות.", benefits: ["הפחתה טבעית של התיאבון", "צמצום כפייתיות האכילה", "איזון מחדש הורמונלי אנדוקריני", "תוכנית תזונה אישית", "מעקב לאורך זמן לתוצאות מתמשכות"] },
        { title: "גמילה מעישון", subtitle: "פרוטוקול גמילה עדין", description: "הלוקסופונקטורה מגרה את ייצור האנדורפינים הטבעיים, ומפחיתה משמעותית את תסמיני הגמילה ואת הרצון לעשן. ליווי מקיף לחופש מוחלט.", benefits: ["הפחתה מהירה של הדחף לעשן", "הקלת תסמיני הגמילה", "גירוי טבעי של אנדורפינים", "ניהול לחץ לאחר הפסקת העישון", "מניעת עלייה במשקל הנלווית"] },
        { title: "שינה ורלקסציה", subtitle: "מצאו מחדש שינה איכותית", description: "על ידי פעולה על המרידיאנים הקשורים למחזור הצירקדי, הלוקסופונקטורה עוזרת לווסת את השינה באופן טבעי ולהפחית לחץ כרוני, ללא שימוש בתרופות.", benefits: ["ויסות מחזור הצירקדי", "הפחתת לחץ וחרדה", "שיפור איכות השינה", "רלקסציה עמוקה מהסשן הראשון", "חלופה טבעית לכדורי שינה"] },
        { title: "התחדשות פנים", subtitle: "זוהר טבעי, ללא הזרקות", description: "גירוי אור אינפרא-אדום מפעיל באופן טבעי את ייצור הקולגן והאלסטין. טיפול לא פולשני המגלה את זוהר עורכם.", benefits: ["גירוי טבעי של קולגן", "שיפור גוון העור והזוהר", "הפחתת קמטוטים", "הידוק עור ניכר", "ללא הזרקות, ללא כאב"] },
        { title: "ניהול התמכרויות", subtitle: "איזון מחדש עמוק של מערכת העצבים", description: "הלוקסופונקטורה מציעה תמיכה יקרת ערך בטיפול בהתנהגויות ממכרות על ידי איזון מחדש של המערכת האנדוקרינית וקידום הייצור הטבעי של נוירוטרנסמיטורים.", benefits: ["איזון מחדש של המערכת האנדוקרינית", "תמיכה בגמילה התנהגותית", "גירוי נוירוטרנסמיטורים של רווחה", "ליווי כולל ואישי", "גישה לא תרופתית"] },
        { title: "רווחה וגיל המעבר", subtitle: "שלווה ואיזון הורמונלי", description: "הלוקסופונקטורה מציעה מענה קליני לשיבושים ההורמונליים של גיל המעבר. על ידי ויסות המערכת האנדוקרינית, פרוטוקול זה מפחית את אי הנוחות הפיזית והרגשית.", benefits: ["הפחתה משמעותית של גלי חום", "שיפור מצב הרוח ואיכות השינה", "שליטה בדמות ורטנציה של מים", "ליווי תזונתי מטבולי מותאם", "גישה טבעית ללא הורמונים סינתטיים", "עייפות ודכאון"] },
      ],
    },
    servicesPreview: {
      s1title: "תזונה קלינית", s1desc: "תוכניות תזונה אישיות המבוססות על ניתוח מדעי מדויק של צרכיכם.", s1note: "מרשם המותאם לפרופיל הביולוגי שלכם",
      s7title: "רווחה וגיל המעבר", s7desc: "חציית המעבר ההורמונלי הזה בנוחות וחיוניות. פרוטוקול ספציפי להפחתת גלי חום, ויסות מצב הרוח ושמירה על הדמות.", s7note: "פרוטוקול הורמונלי טבעי",
      s2title: "ירידה במשקל", s2desc: "הפחתת כפייתיות אכילה באמצעות לוקסופונקטורה וליווי תזונתי מותאם.", s2note: "גירוי נקודות רפלקס אנדוקריניות",
      s3title: "גמילה מעישון", s3desc: "פרוטוקול גמילה מעישון המשלב לוקסופונקטורה וליווי אישי.", s3note: "פעולה על קולטני ההתמכרות",
      s4title: "שינה ורלקסציה", s4desc: "שיפור איכות השינה וניהול לחץ באמצעות גירוי אינפרא-אדום.", s4note: "ויסות מחזור הצירקדי",
      s5title: "התחדשות פנים", s5desc: "גירוי טבעי של ייצור קולגן ואלסטין על ידי אור.", s5note: "הפעלה תאית לא פולשנית",
      s6title: "התמכרויות", s6desc: "טיפול בהתנהגויות ממכרות באמצעות לוקסופונקטורה ומעקב כולל.", s6note: "איזון מחדש של המערכת האנדוקרינית",
    },
    luxo: {
      heroBadge: "טכנולוגיית רפלקס אינפרא-אדום",
      heroTitle1: "לוקסופונקטורה®",
      heroTitle2: "חדשנות דרך האור",
      heroDesc: "טכנולוגיית רפלקס בקרינה אינפרא-אדומה, לא פולשנית וללא כאב, בהמשך לטכניקות האנרגיה העתיקות. היא משחזרת את האיזון התפקודי של הגוף על ידי פעולה על מערכות ההורמונים, העיכול והלימפה.",
      howBadge: "אופן הפעולה",
      howTitle: "כיצד פועלת הלוקסופונקטורה®?",
      howP1: "אנרגיית הקרינה האינפרא-אדומה מועברת לסיבי העצב המרכיבים את נקודת הרפלקס. גירוי זה פועל על <strong>המערכת העצבית האוטונומית</strong>, במטרה לשחזר את האיזון התפקודי של המערכת ההורמונלית.",
      howP2: "שני איברים מפתח ממוקדים: <strong>ההיפותלמוס וההיפופיזה</strong>, הממוקמים במוח, המווסתים את המערכת העצבית האוטונומית, הפרשת נוירוהורמונים ותפקודים התנהגותיים.",
      howP3: "הטיפולים מתקיימים בקצב של <strong>סשן אחד של 30 דקות בשבוע</strong>, במהלכו מגורות כ-30 נקודות. הטכניקה עדינה, ללא כאב, לא פולשנית וללא סיכון.",
      hormonesBadge: "מנגנון הורמונלי",
      hormonesTitle: "4 הורמונים חיוניים מאוזנים מחדש",
      hormonesDesc: "ארבעת ההורמונים הללו ממלאים תפקיד חיוני ברגשותינו, תנודות מצב הרוח וההתנהגות שלנו. הלוקסופונקטורה® תורמת באופן טבעי לאיזונם מחדש.",
      h1name: "אנדורפין", h1sub: "הורמון הרווחה", h1desc: "משוחרר בזמן מאמץ גופני, הוא מספק תחושת רווחה ושלמות. יש לו גם פעולה משככת כאבים. חסר בו עלול לגרום לעצבנות וגירוי.",
      h2name: "דופמין", h2sub: "הורמון ההנאה", h2desc: "מחסור בדופמין קשור לחוסר עניין בחיים, אפילו לדיכאון. הוא גם עלול להגביר את הדחף הבלתי ניתן לעצירה לאכול מזון מתוק או שמן, לעשן...",
      h3name: "סרוטונין", h3sub: "הורמון האושר", h3desc: "יש לו אפקט אנטי-דיכאוני ומווסת את תחושת השובע. רמה אופטימלית מונעת משיכה לסוכר. חסר בו מעודד נשנוש כפייתי ועלייה במשקל.",
      h4name: "מלטונין", h4sub: "הורמון השינה", h4desc: "מסונתז מסרוטונין, הוא מווסת את השעון הביולוגי שלנו. כשהוא חסר, ההירדמות קשה, השינה מופרעת, עם סיכון לחרדה ולהתמכרויות.",
      benefitsTitle: "למה לבחור בלוקסופונקטורה®?",
      b1title: "לא פולשני", b1desc: "ללא מחטים, ללא כאב. קרן אינפרא-אדומה ללא כאב מגרה נקודות רפלקס.",
      b2title: "ללא תופעות לוואי", b2desc: "טכניקה טבעית, ללא חומרים כימיים או תרופות.",
      b3title: "סשנים של 30 דקות", b3desc: "סשן אחד בשבוע, כ-30 נקודות מגורות, תוצאות הדרגתיות ומתמשכות.",
      b4title: "רב-תכליתי", b4desc: "התמכרויות, משקל, שינה, לחץ, גיל המעבר, התחדשות — פרוטוקול אחד.",
      b5title: "רווחה כוללת", b5desc: "מאזן מחדש באופן טבעי אנדורפינים, דופמין, סרוטונין ומלטונין.",
      b6title: "מבוסס מדעית", b6desc: "מבוסס על רפלקסולוגיה וגירוי המערכת העצבית האוטונומית (היפותלמוס / היפופיזה).",
      indicationsTitle: "אינדיקציות",
      indicationsDesc: "הלוקסופונקטורה® יעילה במיוחד לאיזון מחדש של הגוף ו:",
      i1: "ירידה במשקל והפחתת כפייתיות אכילה",
      i2: "גמילה מעישון וניהול התמכרויות (עישון, אלכוהול...)",
      i3: "רלקסציה עמוקה וניהול לחץ כרוני",
      i4: "שיפור איכות השינה",
      i5: "התחדשות פנים טבעית וטיפול בעור הפנים",
      i6: "הפרעות הקשורות לגיל המעבר",
      i7: "חרדה והפרעות מצב רוח",
      i8: "הפרעות התנהגות אכילה",
      faqBadge: "שאלות נפוצות",
      faqTitle: "כל מה שצריך לדעת על לוקסופונקטורה®",
      faq1q: "מה ההבדל מאקופונקטורה ודיגיטופונקטורה?", faq1a: "3 הטכניקות מבוססות על גירוי נקודות רפלקס ואאוריקולותרפיה. לוקסופונקטורה® משתמשת בקרן אינפרא-אדומה ללא כאב. אקופונקטורה היא פרוצדורה רפואית עם מחטים. דיגיטופונקטורה משתמשת בלחץ מכני של אצבע או עט.",
      faq2q: "האם ההשפעות נמשכות לאורך זמן?", faq2a: "כן, ההשפעות נמשכות היטב לאורך זמן. במידת הצורך, ניתן לבצע סשנים לתחזוקה לאחר הטיפול הראשוני.",
      faq3q: "מאיזה גיל ניתן לקבל לוקסופונקטורה®?", faq3a: "ניתן לטפל בילדים ומתבגרים. לירידה במשקל של צעירים בשלב הצמיחה, יש לבצע מעקב תזונתי תחת פיקוח רפואי.",
      faq4q: "האם ניתן להפסיק טיפול בזמן חופשה?", faq4a: "טיפולי הרזיה, רלקסציה ופנים ניתן להפסיק. לגמילה מעישון (3 עד 5 ימים רצופים), עדיף להימנע מכל הפסקה.",
      faq5q: "האם יש התוויות נגד?", faq5a: "כאמצעי זהירות, הטיפולים אינם מומלצים לנשים בהריון, לאנשים עם מחלות קשות או הפרעות אפילפטיות. הרזיה בילדים גדלים מחייבת פיקוח רפואי.",
      faq6q: "האם קיימות מחקרים מדעיים על לוקסופונקטורה®?", faq6a: "כן. נערכו מחקרים קליניים, כולל הערכה קלינית עצמאית (ד\"ר Vaillant) ומחקר על תסמיני טרום גיל המעבר. עבודות אלה מוכיחות את יעילות הטכניקה ואת סבילותה.",
      ctaTitle: "נסו את הלוקסופונקטורה®",
      ctaDesc: "קבעו את הסשן הראשון שלכם וגלו את היתרונות של טכניקה חדשנית זו, בהנחיית המומחיות של ד\"ר רונית קלפון.",
      ctaBtn: "הזמנת סשן",
    },
  },
  ru: {
    nav: {
      home: "Главная",
      services: "Услуги",
      luxopuncture: "Люксопунктура",
      about: "О нас",
      contact: "Контакты",
      rdv: "Записаться",
      pricing: "Тарифы",
    },
    hero: {
      badge: "Доктор фармации",
      title1: "Обретите равновесие",
      title2: "и природное благополучие",
      subtitle: "Клиническое питание, персональное диетическое сопровождение и люксопунктура. Уникальный подход, основанный на фармацевтической экспертизе, в сердце Тель-Авива.",
      cta: "Записаться на приём",
      services: "Узнать об услугах",
      certified: "Сертифицированный специалист",
      centre: "Аккредитованный центр Luxomed",
      stat1: "Лет опыта",
      stat2: "Частная клиника",
      stat3: "Обучение",
      stat3label: "Во Франции",
      luxoCardDesc: "Неинвазивная техника инфракрасного света для комплексного благополучия",
    },
    services: {
      badge: "Экосистема лечения",
      title: "Ваши цели — наша экспертиза",
      subtitle: "Каждый курс лечения разработан с точностью врача-фармацевта и мягкостью холистического подхода.",
      more: "Все услуги",
      pageTitle: "Совершенство на службе вашего здоровья",
      pageSubtitle: "Полный спектр услуг — от клинического питания до люксопунктуры, разработанный с точностью доктора фармации.",
      pageLabel: "Наши услуги",
      cta: "Готовы начать?",
      ctaDesc: "Каждый путь начинается с первой консультации. Запишитесь, чтобы узнать о программе, подобранной под ваши нужды.",
      ctaBtn: "Записаться на консультацию",
      rdvBtn: "Записаться на приём",
    },
    process: {
      badge: "Протокол лечения",
      title: "Как проходит наблюдение?",
      subtitle: "Персональное сопровождение, шаг за шагом, чтобы помочь вам достичь целей надолго.",
      step: "Шаг",
      s1title: "Углублённый анализ",
      s1desc: "Комплексная оценка с учётом вашей медицинской истории, пищевых привычек и личных целей.",
      s1detail: "Биологические исследования и фармацевтический анамнез",
      s2title: "Молекулярный баланс",
      s2desc: "Разработка точного нутрициологического протокола, обогащённого экспертизой клинической фармакологии.",
      s2detail: "Микро- и макронутриенты в точных дозах",
      s3title: "Люксопунктура®",
      s3desc: "Целевые сеансы люксопунктуры для стимуляции рефлекторных точек и восстановления баланса эндокринной системы.",
      s3detail: "Неинвазивный инфракрасный свет на меридианах",
      s4title: "Долгосрочная жизненность",
      s4desc: "Постоянный мониторинг и корректировки для обеспечения устойчивых результатов и ежедневного благополучия.",
      s4detail: "Контрольные консультации и переоценка",
    },
    clinic: {
      badge: "Наше пространство",
      title: "Медицинский кабинет в сердце Тель-Авива",
      desc: "В спокойной и конфиденциальной обстановке доктор Кальфон принимает пациентов по предварительной записи для углублённых консультаций. Каждый случай индивидуален, с соблюдением врачебной тайны.",
      f1title: "Индивидуальное медицинское наблюдение",
      f1desc: "Каждая консультация адаптирована к вашему профилю, истории болезни и целям",
      f2title: "Приём по записи",
      f2desc: "В центре Тель-Авива, доступно и конфиденциально",
      f3title: "Спокойная атмосфера",
      f3desc: "Пространство, созданное для гармонии и качества лечения",
    },
    cta: {
      title1: "Начните своё преображение",
      title2: "Уже сегодня",
      subtitle: "Запишитесь на первую консультацию и узнайте, как союз науки и инноваций может изменить ваше самочувствие.",
      btn: "Записаться на приём",
    },
    contact: {
      serviceOptions: [
        { value: "nutrition", label: "Питание и диетическое наблюдение" },
        { value: "luxopuncture_weight", label: "Люксопунктура — Снижение веса" },
        { value: "luxopuncture_smoking", label: "Люксопунктура — Отказ от курения" },
        { value: "luxopuncture_addiction", label: "Люксопунктура — Зависимости" },
        { value: "luxopuncture_sleep", label: "Люксопунктура — Сон" },
        { value: "luxopuncture_relaxation", label: "Люксопунктура — Расслабление" },
        { value: "luxopuncture_rejuvenation", label: "Люксопунктура — Омоложение лица" },
      ],
      label: "Контакты",
      title: "Запись на приём",
      pageSubtitle: "Свяжитесь с нами для записи на первую консультацию или по любым вопросам об услугах.",
      subtitle: "Заполните форму ниже, и мы свяжемся с вами для подтверждения записи.",
      formTitle: "Форма записи",
      name: "Полное имя",
      namePlaceholder: "Ваше имя",
      email: "Email",
      emailPlaceholder: "your@email.com",
      phone: "Телефон",
      service: "Желаемая услуга",
      serviceSelect: "Выберите услугу",
      mode: "Формат консультации *",
      presentiel: "Очно",
      presentielSub: "Тель-Авив",
      visio: "Видеозвонок",
      visioSub: "Zoom / Teams",
      date: "Предпочтительная дата",
      message: "Сообщение",
      messagePlaceholder: "Кратко опишите вашу потребность...",
      send: "Отправить запрос",
      sending: "Отправка...",
      successTitle: "Спасибо!",
      success: "Ваш запрос на запись получен. Мы свяжемся с вами в ближайшее время.",
      newRdv: "Новая запись",
      infoTitle: "Информация",
      address: "Адрес",
      addressVal: "Тель-Авив, Израиль",
      hours: "Часы работы",
      hoursVal1: "Воскресенье – Четверг",
      hoursVal2: "9:00 – 18:00",
      chatTitle: "Онлайн-чат",
      chatDesc: "Нужен быстрый ответ? Воспользуйтесь чатом, нажав на иконку в правом нижнем углу экрана.",
      chatAvailable: "Доступен сейчас",
    },
    chat: {
      title: "Виртуальный ассистент",
      online: "Онлайн",
      heading: "Онлайн-чат",
      intro: "Задайте ваши вопросы, мы ответим быстро.",
      namePlaceholder: "Ваше имя",
      emailPlaceholder: "Ваш email",
      start: "Начать разговор",
      welcome: (name) => `Здравствуйте, ${name}! Добро пожаловать. Чем мы можем помочь вам сегодня?`,
      inputPlaceholder: "Введите ваше сообщение...",
    },
    about: {
      label: "О нас",
      title: "Д-р Ронит Кальфон",
      subtitle: "Доктор фармации · Питание · Люксопунктура",
      bio1: "Доктор фармации по образованию, д-р Ронит Кальфон посвятила карьеру пересечению фармацевтической науки и холистического благополучия.",
      bio2: "Её уникальная экспертиза в фармакологии позволяет предлагать нутрициологические рецепты исключительной точности, с учётом всех взаимодействий и биологических потребностей пациентов.",
      bio3: "Базируясь в сердце Тель-Авива, она сопровождает пациентов комплексным подходом, сочетающим клиническое питание, персональное диетическое наблюдение и люксопунктуру.",
      stat1: "Доктор фармации",
      stat2: "Лет опыта",
      stat3: "Пациентов",
      stat4: "Специализации",
      journeyTitle: "Профессиональный путь",
      journeySubtitle: "Путь, направляемый научной строгостью и страстью к лечению.",
      approachTitle: "Мой подход",
      approach1title: "Фармацевтическая точность на службе питания.",
      approach1: "Мой опыт доктора фармации даёт мне глубокое понимание биологических механизмов. Каждый нутрициологический рецепт разрабатывается с той же строгостью, что и медицинский.",
      approach2title: "Люксопунктура как катализатор.",
      approach2: "В дополнение к нутрициологическому наблюдению люксопунктура действует непосредственно на эндокринную систему, ускоряя и закрепляя результаты.",
      approach3title: "Человеческий подход.",
      approach3: "Помимо науки, каждый пациент уникален. Я придаю первостепенное значение умению слушать и адаптировать каждый протокол.",
      contactBtn: "Связаться",
      m1year: "Докторантура", m1title: "Доктор фармации", m1desc: "Углублённая подготовка по фармакологии, биохимии и фармацевтическим наукам.",
      m2year: "Специализация", m2title: "Клиническое питание", m2desc: "Экспертиза в микронутриционистике и персональном диетическом сопровождении.",
      m3year: "Инновация", m3title: "Люксопунктура", m3desc: "Подготовка и сертификация по методам рефлексотерапии инфракрасным светом.",
      m4year: "Сегодня", m4title: "Клиника в Тель-Авиве", m4desc: "Клиника, посвящённая комплексному благополучию, в сердце Тель-Авива.",
    },
    footer: {
      bio: "Доктор фармации, специалист по питанию, диетическому наблюдению и люксопунктуре. Научный и персональный подход в сердце Тель-Авива.",
      servicesTitle: "Услуги",
      s1: "Питание и диетология", s2: "Люксопунктура", s3: "Отказ от курения", s4: "Управление весом",
      navTitle: "Навигация",
      rights: "Все права защищены.",
    },
    servicesPage: {
      s: [
        { title: "Клиническое питание и диетическое наблюдение", subtitle: "Программа на заказ, основанная на науке", description: "Благодаря докторантуре в области фармации д-р Кальфон разрабатывает нутрициологические программы непревзойдённой точности. Каждый рецепт учитывает ваш полный биологический профиль, лекарственные взаимодействия и конкретные физиологические потребности.", benefits: ["Углублённая и персонализированная нутрициологическая оценка", "Диетические планы, адаптированные к вашему медицинскому профилю", "Регулярное наблюдение и динамические корректировки", "Целевая нутрициологическая поддержка", "Учёт лекарственных взаимодействий"] },
        { title: "Снижение веса", subtitle: "Освободитесь от пищевых компульсий", description: "Люксопунктура воздействует на рефлекторные точки эндокринной системы для естественного снижения пищевых компульсий. В сочетании с тщательным диетическим наблюдением этот подход обеспечивает долгосрочные результаты.", benefits: ["Естественное снижение аппетита", "Уменьшение пищевых компульсий", "Эндокринный гормональный ребаланс", "Персонализированная диетическая программа", "Долгосрочное наблюдение для устойчивых результатов"] },
        { title: "Отказ от курения", subtitle: "Мягкий протокол отказа", description: "Люксопунктура стимулирует выработку природных эндорфинов, значительно снижая симптомы отмены и тягу. Комплексное сопровождение для окончательного освобождения.", benefits: ["Быстрое снижение тяги к курению", "Ослабление симптомов отмены", "Естественная стимуляция эндорфинов", "Управление стрессом после отказа", "Профилактика сопутствующего набора веса"] },
        { title: "Сон и расслабление", subtitle: "Обретите снова полноценный сон", description: "Воздействуя на меридианы, связанные с циркадным циклом, люксопунктура помогает естественно регулировать сон и снижать хронический стресс без применения лекарств.", benefits: ["Регуляция циркадного цикла", "Снижение стресса и тревоги", "Улучшение качества сна", "Глубокое расслабление с первого сеанса", "Природная альтернатива снотворным"] },
        { title: "Омоложение лица", subtitle: "Естественное сияние без инъекций", description: "Стимуляция инфракрасным светом естественным образом активирует выработку коллагена и эластина. Неинвазивный уход, раскрывающий сияние вашей кожи.", benefits: ["Естественная стимуляция коллагена", "Улучшение тона и сияния кожи", "Уменьшение мелких морщин", "Видимое укрепление кожи", "Ноль инъекций, ноль боли"] },
        { title: "Управление зависимостями", subtitle: "Глубокий ребаланс нервной системы", description: "Люксопунктура предлагает ценную поддержку в работе с зависимым поведением, восстанавливая баланс эндокринной системы и способствуя естественной выработке нейротрансмиттеров.", benefits: ["Восстановление баланса эндокринной системы", "Поддержка поведенческой отмены", "Стимуляция нейротрансмиттеров благополучия", "Комплексное и персонализированное сопровождение", "Безмедикаментозный подход"] },
        { title: "Благополучие и менопауза", subtitle: "Спокойствие и гормональный баланс", description: "Люксопунктура предлагает клинический ответ на гормональные нарушения менопаузы. Регулируя эндокринную систему, этот протокол облегчает физический и эмоциональный дискомфорт.", benefits: ["Значительное снижение приливов и потоотделения", "Улучшение настроения и качества сна", "Контроль фигуры и задержки воды", "Адаптированное метаболическое питательное сопровождение", "Натуральный подход без синтетических гормонов", "Усталость и упадок настроения"] },
      ],
    },
    servicesPreview: {
      s1title: "Клиническое питание", s1desc: "Персональные нутрициологические программы на основе точного фармацевтического анализа ваших потребностей.", s1note: "Рецепт, адаптированный к вашему биологическому профилю",
      s7title: "Благополучие и менопауза", s7desc: "Пройдите этот гормональный переход с комфортом и жизненностью. Специальный протокол для уменьшения приливов, регуляции настроения и сохранения фигуры.", s7note: "Натуральный гормональный протокол",
      s2title: "Снижение веса", s2desc: "Снижение пищевых компульсий с помощью люксопунктуры и персонального диетического наблюдения.", s2note: "Стимуляция эндокринных рефлекторных точек",
      s3title: "Отказ от курения", s3desc: "Протокол отказа от курения, сочетающий люксопунктуру и персональное сопровождение.", s3note: "Воздействие на рецепторы зависимости",
      s4title: "Сон и расслабление", s4desc: "Улучшение качества сна и управление стрессом с помощью инфракрасной стимуляции.", s4note: "Регуляция циркадного ритма",
      s5title: "Омоложение лица", s5desc: "Естественная стимуляция выработки коллагена и эластина с помощью света.", s5note: "Неинвазивная клеточная активация",
      s6title: "Зависимости", s6desc: "Лечение зависимого поведения с помощью люксопунктуры и комплексного наблюдения.", s6note: "Восстановление баланса эндокринной системы",
    },
    luxo: {
      heroBadge: "Инфракрасная рефлекторная технология",
      heroTitle1: "Люксопунктура®",
      heroTitle2: "Инновации через свет",
      heroDesc: "Рефлекторная технология инфракрасного излучения, неинвазивная и безболезненная, продолжающая традиции древних энергетических техник. Она восстанавливает функциональный баланс организма, воздействуя на гормональную, пищеварительную и лимфатическую системы.",
      howBadge: "Механизм действия",
      howTitle: "Как работает Люксопунктура®?",
      howP1: "Энергия инфракрасного излучения передаётся нервным окончаниям, составляющим рефлекторную точку. Эта стимуляция действует на <strong>вегетативную нервную систему</strong>, стремясь восстановить функциональный баланс гормональной системы.",
      howP2: "Два ключевых органа являются мишенями: <strong>гипоталамус и гипофиз</strong>, расположенные в мозге, которые регулируют вегетативную нервную систему, секрецию нейрогормонов и поведенческие функции.",
      howP3: "Процедуры проводятся в режиме <strong>одного сеанса в 30 минут в неделю</strong>, в течение которого стимулируется около тридцати точек. Техника мягкая, безболезненная, неинвазивная и безопасная.",
      hormonesBadge: "Гормональный механизм",
      hormonesTitle: "4 Ключевых гормона восстановлены",
      hormonesDesc: "Эти четыре гормона играют существенную роль в наших ощущениях, перепадах настроения и поведении. Люксопунктура® естественным образом способствует их восстановлению.",
      h1name: "Эндорфин", h1sub: "Гормон благополучия", h1desc: "Выделяемый при физических нагрузках, он даёт чувство благополучия и полноты. Он также обладает обезболивающим действием. Его недостаток может вызвать нервозность и раздражительность.",
      h2name: "Дофамин", h2sub: "Гормон удовольствия", h2desc: "Дефицит дофамина связан с безразличием к жизни, вплоть до депрессии. Он также усиливает непреодолимое желание употреблять сладкую или жирную пищу, курить…",
      h3name: "Серотонин", h3sub: "Гормон счастья", h3desc: "Он оказывает антидепрессивное действие и регулирует чувство насыщения. Оптимальный уровень предотвращает тягу к сахару. Его недостаток способствует компульсивным перекусам и набору веса.",
      h4name: "Мелатонин", h4sub: "Гормон сна", h4desc: "Синтезируемый из серотонина, он регулирует наши биологические часы. При его дефиците засыпание затруднено, сон нарушен, с риском тревоги и зависимостей.",
      benefitsTitle: "Почему выбирают Люксопунктуру®?",
      b1title: "Неинвазивная", b1desc: "Без игл, без боли. Безболезненный инфракрасный луч стимулирует рефлекторные точки.",
      b2title: "Без побочных эффектов", b2desc: "Натуральная техника, без химических веществ и медикаментов.",
      b3title: "Сеансы по 30 мин", b3desc: "Один сеанс в неделю, около тридцати стимулируемых точек, прогрессивные и долгосрочные результаты.",
      b4title: "Универсальная", b4desc: "Зависимости, вес, сон, стресс, менопауза, омоложение — один протокол.",
      b5title: "Комплексное благополучие", b5desc: "Естественно восстанавливает баланс эндорфинов, дофамина, серотонина и мелатонина.",
      b6title: "Научно обоснованная", b6desc: "Основана на рефлексотерапии и стимуляции вегетативной нервной системы (гипоталамус / гипофиз).",
      indicationsTitle: "Показания",
      indicationsDesc: "Люксопунктура® особенно эффективна для восстановления баланса организма и:",
      i1: "Снижение веса и уменьшение пищевых компульсий",
      i2: "Отказ от курения и управление зависимостями (табак, алкоголь…)",
      i3: "Глубокое расслабление и управление хроническим стрессом",
      i4: "Улучшение качества сна",
      i5: "Естественное омоложение лица (кожа лица, лёгкие ноги)",
      i6: "Нарушения, связанные с менопаузой",
      i7: "Тревожные состояния и расстройства настроения",
      i8: "Расстройства пищевого поведения",
      faqBadge: "Часто задаваемые вопросы",
      faqTitle: "Всё о Люксопунктуре®",
      faq1q: "В чём отличие от акупунктуры и дигитопунктуры?", faq1a: "Все 3 техники основаны на стимуляции рефлекторных точек и аурикулотерапии. Люксопунктура® использует безболезненный инфракрасный луч. Акупунктура — медицинская процедура с иглами. Дигитопунктура использует механическое давление пальца или стилуса.",
      faq2q: "Сохраняются ли эффекты со временем?", faq2a: "Да, эффекты сохраняются очень хорошо со временем. При необходимости поддерживающие сеансы могут проводиться после начального курса.",
      faq3q: "С какого возраста можно проходить Люксопунктуру®?", faq3a: "Процедуры могут проводиться детям и подросткам. Для похудения молодых людей в фазе роста диетическое наблюдение должно осуществляться под медицинским контролем.",
      faq4q: "Можно ли прервать курс во время отпуска?", faq4a: "Курсы похудения, релаксации и лица можно прерывать. Для отказа от курения (3-5 последовательных дней) лучше избегать любых перерывов.",
      faq5q: "Есть ли противопоказания?", faq5a: "В целях предосторожности курсы не рекомендуются беременным женщинам, людям с тяжёлыми заболеваниями или эпилептическими расстройствами. Похудение у растущих детей требует медицинского наблюдения.",
      faq6q: "Существуют ли научные исследования о Люксопунктуре®?", faq6a: "Да. Были проведены клинические исследования, включая независимую клиническую оценку (д-р Vaillant) и исследование симптомов пременопаузы. Эти работы демонстрируют эффективность и переносимость техники.",
      ctaTitle: "Попробуйте Люксопунктуру®",
      ctaDesc: "Запишитесь на первый сеанс и откройте для себя преимущества этой инновационной техники под руководством д-ра Ронит Кальфон.",
      ctaBtn: "Записаться на сеанс",
    },
  },
};

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState("fr");
  const isRTL = lang === "he";

  React.useEffect(() => {
    document.documentElement.dir = isRTL ? "rtl" : "ltr";
    document.documentElement.lang = lang;
  }, [lang, isRTL]);

  return (
    <LanguageContext.Provider value={{ lang, setLang, t: translations[lang], isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLang() {
  return useContext(LanguageContext);
}