import React, { createContext, useContext, useState } from "react";

const LanguageContext = createContext();

export const translations = {
  fr: {
    nav: {
      home: "Accueil",
      services: "Services",
      luxopuncture: "Luxopuncture",
      about: "À Propos",
      contact: "Contact",
      rdv: "Prendre RDV",
    },
    hero: {
      badge: "Docteur en Pharmacie",
      title1: "Retrouvez Équilibre",
      title2: "& Bien-être au Naturel",
      subtitle: "Nutrition clinique, suivi diététique personnalisé et luxopuncture. Une approche unique fondée sur l'expertise pharmaceutique, au cœur de Tel Aviv.",
      cta: "Prendre Rendez-vous",
      services: "Découvrir les Services",
      certified: "Praticienne certifiée",
      centre: "Centre Agréé Luxomed",
      stat1: "Ans d'expérience",
      stat2: "Clinique privée",
      stat3: "En France",
      stat3label: "Formée",
    },
    services: {
      badge: "Écosystème de soins",
      title: "Vos Objectifs, Notre Expertise",
      subtitle: "Chaque traitement est conçu avec la rigueur d'un docteur en pharmacie et la douceur d'une approche holistique.",
      more: "Voir tous les services",
    },
    process: {
      badge: "Protocole de soin",
      title: "Comment se déroule un suivi ?",
      subtitle: "Un accompagnement personnalisé, étape par étape, pour vous aider à atteindre vos objectifs durablement.",
      step: "Étape",
    },
    clinic: {
      badge: "Notre espace",
      title: "Un Cabinet Médical au Cœur de Tel Aviv",
      desc: "Dans un cadre calme et confidentiel, le Dr. Kalfon reçoit ses patients sur rendez-vous pour des consultations approfondies. Chaque prise en charge est individualisée, dans le respect du secret médical et du confort du patient.",
      f1title: "Suivi Médical Individualisé",
      f1desc: "Chaque consultation est adaptée à votre profil, vos antécédents et vos objectifs",
      f2title: "Cabinet sur Rendez-vous",
      f2desc: "Situé au cœur de Tel Aviv, accessible et confidentiel",
      f3title: "Environnement Apaisant",
      f3desc: "Un espace pensé pour la sérénité et la qualité de la prise en charge",
    },
    cta: {
      title1: "Commencez Votre Transformation",
      title2: "Dès Aujourd'hui",
      subtitle: "Prenez rendez-vous pour une première consultation et découvrez comment l'alliance de la science et de l'innovation peut transformer votre bien-être.",
      btn: "Prendre Rendez-vous",
    },
    contact: {
      title: "Prendre Rendez-vous",
      subtitle: "Remplissez le formulaire ci-dessous et nous vous contacterons pour confirmer votre rendez-vous.",
      name: "Nom complet",
      email: "Email",
      phone: "Téléphone",
      service: "Service souhaité",
      mode: "Mode de consultation",
      presentiel: "En cabinet",
      visio: "Visioconférence",
      date: "Date souhaitée",
      message: "Message (optionnel)",
      send: "Envoyer la demande",
      success: "Demande envoyée !",
      successMsg: "Nous vous contacterons très prochainement pour confirmer votre rendez-vous.",
    },
  },
  en: {
    nav: {
      home: "Home",
      services: "Services",
      luxopuncture: "Luxopuncture",
      about: "About",
      contact: "Contact",
      rdv: "Book Appointment",
    },
    hero: {
      badge: "Doctor of Pharmacy",
      title1: "Restore Balance",
      title2: "& Natural Well-being",
      subtitle: "Clinical nutrition, personalized dietary follow-up and luxopuncture. A unique approach based on pharmaceutical expertise, in the heart of Tel Aviv.",
      cta: "Book an Appointment",
      services: "Discover Services",
      certified: "Certified practitioner",
      centre: "Luxomed Approved Centre",
      stat1: "Years of experience",
      stat2: "Private clinic",
      stat3: "Trained",
      stat3label: "In France",
    },
    services: {
      badge: "Care ecosystem",
      title: "Your Goals, Our Expertise",
      subtitle: "Each treatment is designed with the rigor of a doctor of pharmacy and the gentleness of a holistic approach.",
      more: "View all services",
    },
    process: {
      badge: "Care protocol",
      title: "How does a follow-up work?",
      subtitle: "Personalized support, step by step, to help you achieve your goals sustainably.",
      step: "Step",
    },
    clinic: {
      badge: "Our space",
      title: "A Medical Practice in the Heart of Tel Aviv",
      desc: "In a calm and confidential setting, Dr. Kalfon receives patients by appointment for in-depth consultations. Each care is individualized, respecting medical confidentiality and patient comfort.",
      f1title: "Individualized Medical Follow-up",
      f1desc: "Each consultation is tailored to your profile, history and objectives",
      f2title: "Appointment-based Practice",
      f2desc: "Located in the heart of Tel Aviv, accessible and confidential",
      f3title: "Soothing Environment",
      f3desc: "A space designed for serenity and quality of care",
    },
    cta: {
      title1: "Start Your Transformation",
      title2: "Today",
      subtitle: "Book your first consultation and discover how the alliance of science and innovation can transform your well-being.",
      btn: "Book an Appointment",
    },
    contact: {
      title: "Book an Appointment",
      subtitle: "Fill in the form below and we will contact you to confirm your appointment.",
      name: "Full name",
      email: "Email",
      phone: "Phone",
      service: "Desired service",
      mode: "Consultation mode",
      presentiel: "In-person",
      visio: "Video conference",
      date: "Preferred date",
      message: "Message (optional)",
      send: "Send request",
      success: "Request sent!",
      successMsg: "We will contact you very soon to confirm your appointment.",
    },
  },
  he: {
    nav: {
      home: "בית",
      services: "שירותים",
      luxopuncture: "לוקסופונקטורה",
      about: "אודות",
      contact: "צור קשר",
      rdv: "קביעת תור",
    },
    hero: {
      badge: "דוקטור לפרמקולוגיה",
      title1: "מצאו מחדש את האיזון",
      title2: "ורווחה טבעית",
      subtitle: "תזונה קלינית, ליווי תזונתי אישי ולוקסופונקטורה. גישה ייחודית המבוססת על מומחיות פרמצויטית, בלב תל אביב.",
      cta: "קביעת תור",
      services: "גלו את השירותים",
      certified: "מטפלת מוסמכת",
      centre: "מרכז מוסמך לוקסומד",
      stat1: "שנות ניסיון",
      stat2: "קליניקה פרטית",
      stat3: "הוסמכה",
      stat3label: "בצרפת",
    },
    services: {
      badge: "מערכת טיפולים",
      title: "המטרות שלכם, המומחיות שלנו",
      subtitle: "כל טיפול מתוכנן עם הקפדה של דוקטור לפרמקולוגיה ועדינות של גישה הוליסטית.",
      more: "לכל השירותים",
    },
    process: {
      badge: "פרוטוקול טיפול",
      title: "כיצד מתנהל מעקב?",
      subtitle: "ליווי אישי, צעד אחר צעד, לעזור לכם להשיג את מטרותיכם לאורך זמן.",
      step: "שלב",
    },
    clinic: {
      badge: "המרחב שלנו",
      title: "קליניקה רפואית בלב תל אביב",
      desc: "בסביבה שקטה וסודית, ד\"ר קלפון מקבלת מטופלים בתיאום מראש לייעוצים מעמיקים. כל טיפול מותאם אישית, תוך כיבוד סודיות רפואית ונוחות המטופל.",
      f1title: "מעקב רפואי אישי",
      f1desc: "כל ייעוץ מותאם לפרופיל, ההיסטוריה והמטרות שלכם",
      f2title: "קליניקה בתיאום מראש",
      f2desc: "בלב תל אביב, נגישה וסודית",
      f3title: "סביבה מרגיעה",
      f3desc: "מרחב המיועד לשלווה ואיכות הטיפול",
    },
    cta: {
      title1: "התחילו את השינוי",
      title2: "היום",
      subtitle: "קבעו את הייעוץ הראשון וגלו כיצד שילוב המדע והחדשנות יכול לשנות את רווחתכם.",
      btn: "קביעת תור",
    },
    contact: {
      title: "קביעת תור",
      subtitle: "מלאו את הטופס ונחזור אליכם לאישור הפגישה.",
      name: "שם מלא",
      email: "אימייל",
      phone: "טלפון",
      service: "שירות מבוקש",
      mode: "אופן הייעוץ",
      presentiel: "פיזי",
      visio: "וידאו",
      date: "תאריך מועדף",
      message: "הודעה (אופציונלי)",
      send: "שליחת הבקשה",
      success: "הבקשה נשלחה!",
      successMsg: "ניצור איתכם קשר בקרוב לאישור התור.",
    },
  },
  ru: {
    nav: {
      home: "Главная",
      services: "Услуги",
      luxopuncture: "Люксопунктура",
      about: "О нас",
      contact: "Контакты",
      rdv: "Записаться",
    },
    hero: {
      badge: "Доктор фармации",
      title1: "Обретите равновесие",
      title2: "и природное благополучие",
      subtitle: "Клиническое питание, персональное диетическое сопровождение и люксопунктура. Уникальный подход, основанный на фармацевтической экспертизе, в сердце Тель-Авива.",
      cta: "Записаться на приём",
      services: "Узнать об услугах",
      certified: "Сертифицированный специалист",
      centre: "Аккредитованный центр Luxomed",
      stat1: "Лет опыта",
      stat2: "Частная клиника",
      stat3: "Обучение",
      stat3label: "Во Франции",
    },
    services: {
      badge: "Экосистема лечения",
      title: "Ваши цели — наша экспертиза",
      subtitle: "Каждый курс лечения разработан с точностью врача-фармацевта и мягкостью холистического подхода.",
      more: "Все услуги",
    },
    process: {
      badge: "Протокол лечения",
      title: "Как проходит наблюдение?",
      subtitle: "Персональное сопровождение, шаг за шагом, чтобы помочь вам достичь целей надолго.",
      step: "Шаг",
    },
    clinic: {
      badge: "Наше пространство",
      title: "Медицинский кабинет в сердце Тель-Авива",
      desc: "В спокойной и конфиденциальной обстановке доктор Кальфон принимает пациентов по предварительной записи для углублённых консультаций. Каждый случай индивидуален, с соблюдением врачебной тайны.",
      f1title: "Индивидуальное медицинское наблюдение",
      f1desc: "Каждая консультация адаптирована к вашему профилю, истории болезни и целям",
      f2title: "Приём по записи",
      f2desc: "В центре Тель-Авива, доступно и конфиденциально",
      f3title: "Спокойная атмосфера",
      f3desc: "Пространство, созданное для гармонии и качества лечения",
    },
    cta: {
      title1: "Начните своё преображение",
      title2: "Уже сегодня",
      subtitle: "Запишитесь на первую консультацию и узнайте, как союз науки и инноваций может изменить ваше самочувствие.",
      btn: "Записаться на приём",
    },
    contact: {
      title: "Запись на приём",
      subtitle: "Заполните форму ниже, и мы свяжемся с вами для подтверждения записи.",
      name: "Полное имя",
      email: "Email",
      phone: "Телефон",
      service: "Желаемая услуга",
      mode: "Формат консультации",
      presentiel: "Очно",
      visio: "Видеозвонок",
      date: "Предпочтительная дата",
      message: "Сообщение (необязательно)",
      send: "Отправить запрос",
      success: "Запрос отправлен!",
      successMsg: "Мы свяжемся с вами в ближайшее время для подтверждения записи.",
    },
  },
};

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState("fr");
  return (
    <LanguageContext.Provider value={{ lang, setLang, t: translations[lang] }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLang() {
  return useContext(LanguageContext);
}