import React, { createContext, useContext, useState } from "react";

const LanguageContext = createContext();

export const translations = {
  fr: {
    nav: {
      home: "Accueil",
      services: "Services",
      luxopuncture: "Luxopuncture",
      about: "À Propos",
      contact: "Contact",
      rdv: "Prendre RDV",
    },
    hero: {
      badge: "Docteur en Pharmacie",
      title1: "Retrouvez Équilibre",
      title2: "& Bien-être au Naturel",
      subtitle: "Nutrition clinique, suivi diététique personnalisé et luxopuncture. Une approche unique fondée sur l'expertise pharmaceutique, au cœur de Tel Aviv.",
      cta: "Prendre Rendez-vous",
      services: "Découvrir les Services",
      certified: "Praticienne certifiée",
      centre: "Centre Agréé Luxomed",
      stat1: "Ans d'expérience",
      stat2: "Clinique privée",
      stat3: "En France",
      stat3label: "Formée",
    },
    services: {
      badge: "Écosystème de soins",
      title: "Vos Objectifs, Notre Expertise",
      subtitle: "Chaque traitement est conçu avec la rigueur d'un docteur en pharmacie et la douceur d'une approche holistique.",
      more: "Voir tous les services",
      pageTitle: "L'Excellence au Service de Votre Santé",
      pageSubtitle: "Une gamme complète de soins, de la nutrition clinique à la luxopuncture, conçue avec la rigueur d'un docteur en pharmacie.",
      pageLabel: "Nos Services",
      cta: "Prêt(e) à Commencer ?",
      ctaDesc: "Chaque parcours commence par une première consultation. Prenez rendez-vous pour découvrir le programme adapté à vos besoins.",
      ctaBtn: "Réserver Ma Consultation",
      rdvBtn: "Prendre Rendez-vous",
    },
    process: {
      badge: "Protocole de soin",
      title: "Comment se déroule un suivi ?",
      subtitle: "Un accompagnement personnalisé, étape par étape, pour vous aider à atteindre vos objectifs durablement.",
      step: "Étape",
    },
    clinic: {
      badge: "Notre espace",
      title: "Un Cabinet Médical au Cœur de Tel Aviv",
      desc: "Dans un cadre calme et confidentiel, le Dr. Kalfon reçoit ses patients sur rendez-vous pour des consultations approfondies. Chaque prise en charge est individualisée, dans le respect du secret médical et du confort du patient.",
      f1title: "Suivi Médical Individualisé",
      f1desc: "Chaque consultation est adaptée à votre profil, vos antécédents et vos objectifs",
      f2title: "Cabinet sur Rendez-vous",
      f2desc: "Situé au cœur de Tel Aviv, accessible et confidentiel",
      f3title: "Environnement Apaisant",
      f3desc: "Un espace pensé pour la sérénité et la qualité de la prise en charge",
    },
    cta: {
      title1: "Commencez Votre Transformation",
      title2: "Dès Aujourd'hui",
      subtitle: "Prenez rendez-vous pour une première consultation et découvrez comment l'alliance de la science et de l'innovation peut transformer votre bien-être.",
      btn: "Prendre Rendez-vous",
    },
    contact: {
      label: "Contact",
      title: "Prenez Rendez-vous",
      pageSubtitle: "Contactez-nous pour planifier votre première consultation ou pour toute question sur nos services.",
      subtitle: "Remplissez le formulaire ci-dessous et nous vous contacterons pour confirmer votre rendez-vous.",
      formTitle: "Formulaire de Rendez-vous",
      name: "Nom complet",
      namePlaceholder: "Votre nom",
      email: "Email",
      emailPlaceholder: "votre@email.com",
      phone: "Téléphone",
      service: "Service souhaité",
      serviceSelect: "Sélectionnez un service",
      mode: "Mode de consultation *",
      presentiel: "En Cabinet",
      presentielSub: "Tel Aviv",
      visio: "En Visio",
      visioSub: "Zoom / Teams",
      date: "Date souhaitée",
      message: "Message",
      messagePlaceholder: "Décrivez brièvement votre besoin...",
      send: "Envoyer la Demande",
      sending: "Envoi en cours...",
      successTitle: "Merci !",
      success: "Votre demande de rendez-vous a bien été reçue. Nous vous contacterons dans les plus brefs délais.",
      newRdv: "Nouveau rendez-vous",
      infoTitle: "Informations",
      address: "Adresse",
      addressVal: "Tel Aviv, Israël",
      hours: "Horaires",
      hoursVal1: "Dimanche – Jeudi",
      hoursVal2: "9h00 – 18h00",
      chatTitle: "Chat Direct",
      chatDesc: "Besoin d'une réponse rapide ? Utilisez notre chat en direct en cliquant sur l'icône en bas à droite de votre écran.",
      chatAvailable: "Disponible maintenant",
    },
    about: {
      label: "À propos",
      title: "Dr. Ronit Kalfon",
      subtitle: "Docteur en Pharmacie · Nutrition · Luxopuncture",
      bio1: "Docteur en pharmacie de formation, Dr. Ronit Kalfon a consacré sa carrière à l'intersection de la science pharmaceutique et du bien-être holistique.",
      bio2: "Son expertise unique en pharmacologie lui permet d'offrir des prescriptions nutritionnelles d'une précision exceptionnelle, tenant compte de chaque interaction et de chaque besoin biologique de ses patients.",
      bio3: "Installée au cœur de Tel Aviv, elle accompagne ses patients avec une approche globale mêlant nutrition clinique, suivi diététique personnalisé et luxopuncture — une combinaison rare et particulièrement efficace.",
      stat1: "Docteur en Pharmacie",
      stat2: "Ans d'Expérience",
      stat3: "Patients Accompagnés",
      stat4: "Spécialisations",
      journeyTitle: "Parcours Professionnel",
      journeySubtitle: "Un cheminement guidé par la rigueur scientifique et la passion du soin.",
      approachTitle: "Mon Approche",
      approach1title: "La précision pharmaceutique au service de la nutrition.",
      approach1: "Mon parcours de docteur en pharmacie me confère une compréhension approfondie des mécanismes biologiques. Chaque prescription nutritionnelle est élaborée avec la même rigueur qu'une prescription médicamenteuse.",
      approach2title: "La luxopuncture comme catalyseur.",
      approach2: "En complément du suivi nutritionnel, la luxopuncture permet d'agir directement sur le système endocrinien, accélérant et pérennisant les résultats.",
      approach3title: "Un accompagnement humain.",
      approach3: "Au-delà de la science, chaque patient est unique. J'accorde une importance fondamentale à l'écoute et à l'adaptation de chaque protocole.",
      contactBtn: "Me Contacter",
      m1year: "Doctorat", m1title: "Docteur en Pharmacie", m1desc: "Formation approfondie en pharmacologie, biochimie et sciences du médicament.",
      m2year: "Spécialisation", m2title: "Nutrition Clinique", m2desc: "Expertise en micronutrition et suivi diététique personnalisé.",
      m3year: "Innovation", m3title: "Luxopuncture", m3desc: "Formation et certification en techniques de luminothérapie réflexe.",
      m4year: "Aujourd'hui", m4title: "Clinique Tel Aviv", m4desc: "Cabinet dédié au bien-être global, au cœur de Tel Aviv.",
    },
  },
  en: {
    nav: {
      home: "Home",
      services: "Services",
      luxopuncture: "Luxopuncture",
      about: "About",
      contact: "Contact",
      rdv: "Book Appointment",
    },
    hero: {
      badge: "Doctor of Pharmacy",
      title1: "Restore Balance",
      title2: "& Natural Well-being",
      subtitle: "Clinical nutrition, personalized dietary follow-up and luxopuncture. A unique approach based on pharmaceutical expertise, in the heart of Tel Aviv.",
      cta: "Book an Appointment",
      services: "Discover Services",
      certified: "Certified practitioner",
      centre: "Luxomed Approved Centre",
      stat1: "Years of experience",
      stat2: "Private clinic",
      stat3: "Trained",
      stat3label: "In France",
    },
    services: {
      badge: "Care ecosystem",
      title: "Your Goals, Our Expertise",
      subtitle: "Each treatment is designed with the rigor of a doctor of pharmacy and the gentleness of a holistic approach.",
      more: "View all services",
      pageTitle: "Excellence in the Service of Your Health",
      pageSubtitle: "A complete range of care, from clinical nutrition to luxopuncture, designed with the rigor of a doctor of pharmacy.",
      pageLabel: "Our Services",
      cta: "Ready to Start?",
      ctaDesc: "Every journey begins with a first consultation. Book an appointment to discover the program tailored to your needs.",
      ctaBtn: "Book My Consultation",
      rdvBtn: "Book an Appointment",
    },
    process: {
      badge: "Care protocol",
      title: "How does a follow-up work?",
      subtitle: "Personalized support, step by step, to help you achieve your goals sustainably.",
      step: "Step",
    },
    clinic: {
      badge: "Our space",
      title: "A Medical Practice in the Heart of Tel Aviv",
      desc: "In a calm and confidential setting, Dr. Kalfon receives patients by appointment for in-depth consultations. Each care is individualized, respecting medical confidentiality and patient comfort.",
      f1title: "Individualized Medical Follow-up",
      f1desc: "Each consultation is tailored to your profile, history and objectives",
      f2title: "Appointment-based Practice",
      f2desc: "Located in the heart of Tel Aviv, accessible and confidential",
      f3title: "Soothing Environment",
      f3desc: "A space designed for serenity and quality of care",
    },
    cta: {
      title1: "Start Your Transformation",
      title2: "Today",
      subtitle: "Book your first consultation and discover how the alliance of science and innovation can transform your well-being.",
      btn: "Book an Appointment",
    },
    contact: {
      label: "Contact",
      title: "Book an Appointment",
      pageSubtitle: "Contact us to schedule your first consultation or for any questions about our services.",
      subtitle: "Fill in the form below and we will contact you to confirm your appointment.",
      formTitle: "Appointment Form",
      name: "Full name",
      namePlaceholder: "Your name",
      email: "Email",
      emailPlaceholder: "your@email.com",
      phone: "Phone",
      service: "Desired service",
      serviceSelect: "Select a service",
      mode: "Consultation mode *",
      presentiel: "In Person",
      presentielSub: "Tel Aviv",
      visio: "Video Call",
      visioSub: "Zoom / Teams",
      date: "Preferred date",
      message: "Message",
      messagePlaceholder: "Briefly describe your need...",
      send: "Send Request",
      sending: "Sending...",
      successTitle: "Thank you!",
      success: "Your appointment request has been received. We will contact you as soon as possible.",
      newRdv: "New appointment",
      infoTitle: "Information",
      address: "Address",
      addressVal: "Tel Aviv, Israel",
      hours: "Hours",
      hoursVal1: "Sunday – Thursday",
      hoursVal2: "9:00 – 18:00",
      chatTitle: "Live Chat",
      chatDesc: "Need a quick answer? Use our live chat by clicking the icon at the bottom right of your screen.",
      chatAvailable: "Available now",
    },
    about: {
      label: "About",
      title: "Dr. Ronit Kalfon",
      subtitle: "Doctor of Pharmacy · Nutrition · Luxopuncture",
      bio1: "Trained as a doctor of pharmacy, Dr. Ronit Kalfon has dedicated her career to the intersection of pharmaceutical science and holistic well-being.",
      bio2: "Her unique expertise in pharmacology allows her to offer nutritional prescriptions of exceptional precision, taking into account every interaction and biological need of her patients.",
      bio3: "Based in the heart of Tel Aviv, she supports her patients with a global approach combining clinical nutrition, personalized dietary follow-up, and luxopuncture — a rare and particularly effective combination.",
      stat1: "Doctor of Pharmacy",
      stat2: "Years of Experience",
      stat3: "Patients Supported",
      stat4: "Specializations",
      journeyTitle: "Professional Journey",
      journeySubtitle: "A path guided by scientific rigor and a passion for care.",
      approachTitle: "My Approach",
      approach1title: "Pharmaceutical precision in the service of nutrition.",
      approach1: "My background as a doctor of pharmacy gives me a deep understanding of biological mechanisms. Each nutritional prescription is developed with the same rigor as a medical prescription.",
      approach2title: "Luxopuncture as a catalyst.",
      approach2: "In addition to nutritional follow-up, luxopuncture acts directly on the endocrine system, accelerating and sustaining results.",
      approach3title: "A human approach.",
      approach3: "Beyond science, every patient is unique. I place fundamental importance on listening and adapting each protocol.",
      contactBtn: "Contact Me",
      m1year: "Doctorate", m1title: "Doctor of Pharmacy", m1desc: "In-depth training in pharmacology, biochemistry and pharmaceutical sciences.",
      m2year: "Specialization", m2title: "Clinical Nutrition", m2desc: "Expertise in micronutrition and personalized dietary follow-up.",
      m3year: "Innovation", m3title: "Luxopuncture", m3desc: "Training and certification in reflex light therapy techniques.",
      m4year: "Today", m4title: "Tel Aviv Clinic", m4desc: "Practice dedicated to global well-being, in the heart of Tel Aviv.",
    },
  },
  he: {
    nav: {
      home: "בית",
      services: "שירותים",
      luxopuncture: "לוקסופונקטורה",
      about: "אודות",
      contact: "צור קשר",
      rdv: "קביעת תור",
    },
    hero: {
      badge: "דוקטור לפרמקולוגיה",
      title1: "מצאו מחדש את האיזון",
      title2: "ורווחה טבעית",
      subtitle: "תזונה קלינית, ליווי תזונתי אישי ולוקסופונקטורה. גישה ייחודית המבוססת על מומחיות פרמצויטית, בלב תל אביב.",
      cta: "קביעת תור",
      services: "גלו את השירותים",
      certified: "מטפלת מוסמכת",
      centre: "מרכז מוסמך לוקסומד",
      stat1: "שנות ניסיון",
      stat2: "קליניקה פרטית",
      stat3: "הוסמכה",
      stat3label: "בצרפת",
    },
    services: {
      badge: "מערכת טיפולים",
      title: "המטרות שלכם, המומחיות שלנו",
      subtitle: "כל טיפול מתוכנן עם הקפדה של דוקטור לפרמקולוגיה ועדינות של גישה הוליסטית.",
      more: "לכל השירותים",
      pageTitle: "מצוינות בשירות בריאותכם",
      pageSubtitle: "מגוון מלא של טיפולים, מתזונה קלינית ועד לוקסופונקטורה, מתוכנן בדקדקנות של דוקטור לפרמקולוגיה.",
      pageLabel: "השירותים שלנו",
      cta: "מוכנים להתחיל?",
      ctaDesc: "כל מסע מתחיל בייעוץ ראשון. קבעו תור לגלות את התוכנית המותאמת לצרכיכם.",
      ctaBtn: "הזמנת ייעוץ",
      rdvBtn: "קביעת תור",
    },
    process: {
      badge: "פרוטוקול טיפול",
      title: "כיצד מתנהל מעקב?",
      subtitle: "ליווי אישי, צעד אחר צעד, לעזור לכם להשיג את מטרותיכם לאורך זמן.",
      step: "שלב",
    },
    clinic: {
      badge: "המרחב שלנו",
      title: "קליניקה רפואית בלב תל אביב",
      desc: "בסביבה שקטה וסודית, ד\"ר קלפון מקבלת מטופלים בתיאום מראש לייעוצים מעמיקים. כל טיפול מותאם אישית, תוך כיבוד סודיות רפואית ונוחות המטופל.",
      f1title: "מעקב רפואי אישי",
      f1desc: "כל ייעוץ מותאם לפרופיל, ההיסטוריה והמטרות שלכם",
      f2title: "קליניקה בתיאום מראש",
      f2desc: "בלב תל אביב, נגישה וסודית",
      f3title: "סביבה מרגיעה",
      f3desc: "מרחב המיועד לשלווה ואיכות הטיפול",
    },
    cta: {
      title1: "התחילו את השינוי",
      title2: "היום",
      subtitle: "קבעו את הייעוץ הראשון וגלו כיצד שילוב המדע והחדשנות יכול לשנות את רווחתכם.",
      btn: "קביעת תור",
    },
    contact: {
      label: "צור קשר",
      title: "קביעת תור",
      pageSubtitle: "צרו קשר לתיאום הייעוץ הראשון שלכם או לכל שאלה על השירותים שלנו.",
      subtitle: "מלאו את הטופס ונחזור אליכם לאישור הפגישה.",
      formTitle: "טופס קביעת תור",
      name: "שם מלא",
      namePlaceholder: "שמכם",
      email: "אימייל",
      emailPlaceholder: "your@email.com",
      phone: "טלפון",
      service: "שירות מבוקש",
      serviceSelect: "בחרו שירות",
      mode: "אופן הייעוץ *",
      presentiel: "פיזי",
      presentielSub: "תל אביב",
      visio: "וידאו",
      visioSub: "Zoom / Teams",
      date: "תאריך מועדף",
      message: "הודעה",
      messagePlaceholder: "תארו בקצרה את הצורך שלכם...",
      send: "שליחת הבקשה",
      sending: "שולח...",
      successTitle: "תודה!",
      success: "בקשת התור התקבלה. ניצור איתכם קשר בהקדם.",
      newRdv: "תור חדש",
      infoTitle: "פרטי יצירת קשר",
      address: "כתובת",
      addressVal: "תל אביב, ישראל",
      hours: "שעות פעילות",
      hoursVal1: "ראשון – חמישי",
      hoursVal2: "9:00 – 18:00",
      chatTitle: "צ'אט ישיר",
      chatDesc: "צריכים מענה מהיר? השתמשו בצ'אט החי על ידי לחיצה על הסמל בפינה הימנית התחתונה.",
      chatAvailable: "זמין עכשיו",
    },
    about: {
      label: "אודות",
      title: "ד\"ר רונית קלפון",
      subtitle: "דוקטור לפרמקולוגיה · תזונה · לוקסופונקטורה",
      bio1: "ד\"ר רונית קלפון, בעלת תואר דוקטור בפרמקולוגיה, הקדישה את קריירתה לצומת שבין המדע הפרמצויטי לבין הרווחה ההוליסטית.",
      bio2: "המומחיות הייחודית שלה בפרמקולוגיה מאפשרת לה להציע מרשמים תזונתיים בדיוק יוצא דופן, תוך התחשבות בכל האינטראקציות והצרכים הביולוגיים של מטופליה.",
      bio3: "מתבססת בלב תל אביב, היא מלווה את מטופליה בגישה כוללת המשלבת תזונה קלינית, ליווי תזונתי אישי ולוקסופונקטורה — שילוב נדיר ויעיל במיוחד.",
      stat1: "דוקטור לפרמקולוגיה",
      stat2: "שנות ניסיון",
      stat3: "מטופלים שולוו",
      stat4: "התמחויות",
      journeyTitle: "מסלול מקצועי",
      journeySubtitle: "מסע המונחה על ידי דקדקנות מדעית ותשוקה לטיפול.",
      approachTitle: "הגישה שלי",
      approach1title: "דיוק פרמצויטי בשירות התזונה.",
      approach1: "הרקע שלי כדוקטור לפרמקולוגיה מעניק לי הבנה עמוקה של המנגנונים הביולוגיים. כל מרשם תזונתי מפותח באותה דקדקנות כמו מרשם רפואי.",
      approach2title: "לוקסופונקטורה כמניע.",
      approach2: "בנוסף לליווי התזונתי, הלוקסופונקטורה פועלת ישירות על המערכת האנדוקרינית, מאיצה ומייצבת את התוצאות.",
      approach3title: "ליווי אנושי.",
      approach3: "מעבר למדע, כל מטופל הוא ייחודי. אני מייחסת חשיבות עליונה להקשבה ולהתאמת כל פרוטוקול.",
      contactBtn: "צרו קשר",
      m1year: "דוקטורט", m1title: "דוקטור לפרמקולוגיה", m1desc: "הכשרה מעמיקה בפרמקולוגיה, ביוכימיה ומדעי התרופות.",
      m2year: "התמחות", m2title: "תזונה קלינית", m2desc: "מומחיות במיקרונוטריציה וליווי תזונתי אישי.",
      m3year: "חדשנות", m3title: "לוקסופונקטורה", m3desc: "הכשרה והסמכה בטכניקות רפלקסולוגיה באור אינפרא-אדום.",
      m4year: "היום", m4title: "קליניקה בתל אביב", m4desc: "מרפאה המוקדשת לרווחה כוללת, בלב תל אביב.",
    },
  },
  ru: {
    nav: {
      home: "Главная",
      services: "Услуги",
      luxopuncture: "Люксопунктура",
      about: "О нас",
      contact: "Контакты",
      rdv: "Записаться",
    },
    hero: {
      badge: "Доктор фармации",
      title1: "Обретите равновесие",
      title2: "и природное благополучие",
      subtitle: "Клиническое питание, персональное диетическое сопровождение и люксопунктура. Уникальный подход, основанный на фармацевтической экспертизе, в сердце Тель-Авива.",
      cta: "Записаться на приём",
      services: "Узнать об услугах",
      certified: "Сертифицированный специалист",
      centre: "Аккредитованный центр Luxomed",
      stat1: "Лет опыта",
      stat2: "Частная клиника",
      stat3: "Обучение",
      stat3label: "Во Франции",
    },
    services: {
      badge: "Экосистема лечения",
      title: "Ваши цели — наша экспертиза",
      subtitle: "Каждый курс лечения разработан с точностью врача-фармацевта и мягкостью холистического подхода.",
      more: "Все услуги",
      pageTitle: "Совершенство на службе вашего здоровья",
      pageSubtitle: "Полный спектр услуг — от клинического питания до люксопунктуры, разработанный с точностью доктора фармации.",
      pageLabel: "Наши услуги",
      cta: "Готовы начать?",
      ctaDesc: "Каждый путь начинается с первой консультации. Запишитесь, чтобы узнать о программе, подобранной под ваши нужды.",
      ctaBtn: "Записаться на консультацию",
      rdvBtn: "Записаться на приём",
    },
    process: {
      badge: "Протокол лечения",
      title: "Как проходит наблюдение?",
      subtitle: "Персональное сопровождение, шаг за шагом, чтобы помочь вам достичь целей надолго.",
      step: "Шаг",
    },
    clinic: {
      badge: "Наше пространство",
      title: "Медицинский кабинет в сердце Тель-Авива",
      desc: "В спокойной и конфиденциальной обстановке доктор Кальфон принимает пациентов по предварительной записи для углублённых консультаций. Каждый случай индивидуален, с соблюдением врачебной тайны.",
      f1title: "Индивидуальное медицинское наблюдение",
      f1desc: "Каждая консультация адаптирована к вашему профилю, истории болезни и целям",
      f2title: "Приём по записи",
      f2desc: "В центре Тель-Авива, доступно и конфиденциально",
      f3title: "Спокойная атмосфера",
      f3desc: "Пространство, созданное для гармонии и качества лечения",
    },
    cta: {
      title1: "Начните своё преображение",
      title2: "Уже сегодня",
      subtitle: "Запишитесь на первую консультацию и узнайте, как союз науки и инноваций может изменить ваше самочувствие.",
      btn: "Записаться на приём",
    },
    contact: {
      label: "Контакты",
      title: "Запись на приём",
      pageSubtitle: "Свяжитесь с нами для записи на первую консультацию или по любым вопросам об услугах.",
      subtitle: "Заполните форму ниже, и мы свяжемся с вами для подтверждения записи.",
      formTitle: "Форма записи",
      name: "Полное имя",
      namePlaceholder: "Ваше имя",
      email: "Email",
      emailPlaceholder: "your@email.com",
      phone: "Телефон",
      service: "Желаемая услуга",
      serviceSelect: "Выберите услугу",
      mode: "Формат консультации *",
      presentiel: "Очно",
      presentielSub: "Тель-Авив",
      visio: "Видеозвонок",
      visioSub: "Zoom / Teams",
      date: "Предпочтительная дата",
      message: "Сообщение",
      messagePlaceholder: "Кратко опишите вашу потребность...",
      send: "Отправить запрос",
      sending: "Отправка...",
      successTitle: "Спасибо!",
      success: "Ваш запрос на запись получен. Мы свяжемся с вами в ближайшее время.",
      newRdv: "Новая запись",
      infoTitle: "Информация",
      address: "Адрес",
      addressVal: "Тель-Авив, Израиль",
      hours: "Часы работы",
      hoursVal1: "Воскресенье – Четверг",
      hoursVal2: "9:00 – 18:00",
      chatTitle: "Онлайн-чат",
      chatDesc: "Нужен быстрый ответ? Воспользуйтесь чатом, нажав на иконку в правом нижнем углу экрана.",
      chatAvailable: "Доступен сейчас",
    },
    about: {
      label: "О нас",
      title: "Д-р Ронит Кальфон",
      subtitle: "Доктор фармации · Питание · Люксопунктура",
      bio1: "Доктор фармации по образованию, д-р Ронит Кальфон посвятила карьеру пересечению фармацевтической науки и холистического благополучия.",
      bio2: "Её уникальная экспертиза в фармакологии позволяет предлагать нутрициологические рецепты исключительной точности, с учётом всех взаимодействий и биологических потребностей пациентов.",
      bio3: "Базируясь в сердце Тель-Авива, она сопровождает пациентов комплексным подходом, сочетающим клиническое питание, персональное диетическое наблюдение и люксопунктуру.",
      stat1: "Доктор фармации",
      stat2: "Лет опыта",
      stat3: "Пациентов",
      stat4: "Специализации",
      journeyTitle: "Профессиональный путь",
      journeySubtitle: "Путь, направляемый научной строгостью и страстью к лечению.",
      approachTitle: "Мой подход",
      approach1title: "Фармацевтическая точность на службе питания.",
      approach1: "Мой опыт доктора фармации даёт мне глубокое понимание биологических механизмов. Каждый нутрициологический рецепт разрабатывается с той же строгостью, что и медицинский.",
      approach2title: "Люксопунктура как катализатор.",
      approach2: "В дополнение к нутрициологическому наблюдению люксопунктура действует непосредственно на эндокринную систему, ускоряя и закрепляя результаты.",
      approach3title: "Человеческий подход.",
      approach3: "Помимо науки, каждый пациент уникален. Я придаю первостепенное значение умению слушать и адаптировать каждый протокол.",
      contactBtn: "Связаться",
      m1year: "Докторантура", m1title: "Доктор фармации", m1desc: "Углублённая подготовка по фармакологии, биохимии и фармацевтическим наукам.",
      m2year: "Специализация", m2title: "Клиническое питание", m2desc: "Экспертиза в микронутриционистике и персональном диетическом сопровождении.",
      m3year: "Инновация", m3title: "Люксопунктура", m3desc: "Подготовка и сертификация по методам рефлексотерапии инфракрасным светом.",
      m4year: "Сегодня", m4title: "Клиника в Тель-Авиве", m4desc: "Клиника, посвящённая комплексному благополучию, в сердце Тель-Авива.",
    },
  },
};

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState("fr");
  return (
    <LanguageContext.Provider value={{ lang, setLang, t: translations[lang] }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLang() {
  return useContext(LanguageContext);
}